[package]
name = "ruff-qualia-code"
version = "0.1.0"
edition = "2021"

[dependencies]
ruff_diagnostics = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_macros = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_python_ast = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_python_codegen = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_python_parser = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_python_semantic = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_python_stdlib = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_python_trivia = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_source_file = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }
ruff_text_size = { git = "https://github.com/astral-sh/ruff", tag = "0.12.12" }

[lib]
crate-type = ["cdylib"]
