/**
 * QUALIA.CODE v1.1 - IApplicationInitializerService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IApplicationInitializerService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IApplicationInitializerService } from '../../services/interfaces/IApplicationInitializerService';

/**
 * High-Fidelity Mock for IApplicationInitializerService
 * All methods return type-safe default values
 */
export const mockApplicationInitializerService: IApplicationInitializerService = {
  start: vi.fn().mockResolvedValue(undefined),
};
