/**
 * QUALIA.CODE v1.1 - IAudioContextFactory Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IAudioContextFactory
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IAudioContextFactory } from '../../services/interfaces/IAudioContextFactory';

/**
 * High-Fidelity Mock for IAudioContextFactory
 * All methods return type-safe default values
 */
export const mockAudioContextFactory: IAudioContextFactory = {
  create: vi.fn().mockReturnValue({}),
};
