/**
 * QUALIA.CODE v1.1 - IAudioService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IAudioService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IAudioService } from '../../services/interfaces/IAudioService';

/**
 * High-Fidelity Mock for IAudioService
 * All methods return type-safe default values
 */
export const mockAudioService: IAudioService = {
  start: vi.fn().mockResolvedValue(undefined),
  initializeAudioContext: vi.fn().mockResolvedValue(undefined),
  stop: vi.fn().mockResolvedValue(undefined),
  stopSound: vi.fn().mockReturnValue(undefined),
  getMasterVolume: vi.fn().mockReturnValue(0),
  isRunning: vi.fn().mockReturnValue(false),
  preloadSounds: vi.fn().mockResolvedValue(undefined),
};
