/**
 * QUALIA.CODE v1.1 - IConfigurationService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IConfigurationService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IConfigurationService } from '../../services/interfaces/IConfigurationService';

/**
 * High-Fidelity Mock for IConfigurationService
 * All methods return type-safe default values
 */
export const mockConfigurationService: IConfigurationService = {
  loadConfig: vi.fn().mockResolvedValue({}),
  getConfig: vi.fn().mockReturnValue({}),
  isLoaded: vi.fn().mockReturnValue(false),
  reload: vi.fn().mockResolvedValue(undefined),
};
