/**
 * QUALIA.CODE v1.1 - ICoordinateSystemService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for ICoordinateSystemService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { ICoordinateSystemService } from '../../services/interfaces/ICoordinateSystemService';

/**
 * High-Fidelity Mock for ICoordinateSystemService
 * All methods return type-safe default values
 */
export const mockCoordinateSystemService: ICoordinateSystemService = {
  gridToWorld: vi.fn().mockReturnValue({}),
  worldToScreen: vi.fn().mockReturnValue({}),
  worldToGrid: vi.fn().mockReturnValue({}),
  getGridConfig: vi.fn().mockReturnValue({}),
  indexToGrid: vi.fn().mockReturnValue({}),
};
