/**
 * QUALIA.CODE v1.1 - IDebugService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IDebugService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IDebugService } from '../../services/interfaces/IDebugService';

/**
 * High-Fidelity Mock for IDebugService
 * All methods return type-safe default values
 */
export const mockDebugService: IDebugService = {
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  logServiceStatus: vi.fn().mockReturnValue(undefined),
  logEvent: vi.fn().mockReturnValue(undefined),
  getMetrics: vi.fn().mockReturnValue({
    isRunning: false,
    eventsLogged: 0,
    memoryUsage: 0,
    uptime: 0,
  }),
  getDebugStats: vi.fn().mockReturnValue({
    isRunning: false,
    eventsLogged: 0,
    memoryUsage: 0,
    uptime: 0,
    profilingEnabled: false,
    eventHistory: [],
  }),
  getSystemSnapshot: vi.fn().mockReturnValue({
    timestamp: new Date(),
    services: {},
    performance: {
      memoryUsage: 0,
      uptime: 0,
    },
    eventHistory: [],
  }),
  performAIAnalysis: vi.fn().mockReturnValue([]),
  exportDebugData: vi.fn().mockReturnValue({
    stats: {
      isRunning: false,
      eventsLogged: 0,
      memoryUsage: 0,
      uptime: 0,
      profilingEnabled: false,
      eventHistory: [],
    },
    snapshot: {
      timestamp: new Date(),
      services: {},
      performance: {
        memoryUsage: 0,
        uptime: 0,
      },
      eventHistory: [],
    },
    analysis: [],
    exportTimestamp: 0,
    version: '1.0.0',
  }),
  updateConfig: vi.fn().mockReturnValue(undefined),
  enableProfiling: vi.fn().mockReturnValue(undefined),
  disableProfiling: vi.fn().mockReturnValue(undefined),
  isEnabled: vi.fn().mockReturnValue(false),
  getDebugInterface: vi.fn().mockReturnValue(null),
  attachToGlobalScope: vi.fn().mockReturnValue(undefined),
};
