/**
 * QUALIA.CODE v1.1 - IDebugService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IDebugService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IDebugService } from '../../services/interfaces/IDebugService';

/**
 * High-Fidelity Mock for IDebugService
 * All methods return type-safe default values
 */
export const mockDebugService: IDebugService = {
  logServiceStatus: vi.fn().mockReturnValue(undefined),
  getMetrics: vi.fn().mockReturnValue({}),
  getSystemSnapshot: vi.fn().mockReturnValue({}),
  performAIAnalysis: vi.fn().mockReturnValue({}),
  exportDebugData: vi.fn().mockReturnValue({}),
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  logServiceStatus: vi.fn().mockReturnValue(undefined),
  getDebugStats: vi.fn().mockReturnValue({}),
  getSystemSnapshot: vi.fn().mockReturnValue({}),
  performAIAnalysis: vi.fn().mockReturnValue({}),
  exportDebugData: vi.fn().mockReturnValue({}),
  updateConfig: vi.fn().mockReturnValue(undefined),
  enableProfiling: vi.fn().mockReturnValue(undefined),
  disableProfiling: vi.fn().mockReturnValue(undefined),
  isEnabled: vi.fn().mockReturnValue(false),
  getDebugInterface: vi.fn().mockReturnValue({}),
  attachToGlobalScope: vi.fn().mockReturnValue(undefined),
};
