/**
 * QUALIA.CODE v1.1 - IErrorReportingService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IErrorReportingService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IErrorReportingService } from '../../services/interfaces/IErrorReportingService';

/**
 * High-Fidelity Mock for IErrorReportingService
 * All methods return type-safe default values
 */
export const mockErrorReportingService: IErrorReportingService = {
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  reportError: vi.fn().mockResolvedValue(undefined),
  updateConfig: vi.fn().mockReturnValue(undefined),
  getStatistics: vi.fn().mockReturnValue({
    totalErrors: 0,
    totalBatches: 0,
    successfulReports: 0,
    failedReports: 0,
    duplicatesFiltered: 0,
    averageRetries: 0,
  }),
  exportErrorData: vi.fn().mockReturnValue({
    statistics: {
      totalErrors: 0,
      totalBatches: 0,
      successfulReports: 0,
      failedReports: 0,
      duplicatesFiltered: 0,
      averageRetries: 0,
    },
    recentErrors: [],
    batches: [],
    exportTimestamp: new Date(),
    version: '1.0.0',
  }),
  forceFlush: vi.fn().mockResolvedValue(undefined),
  clearHistory: vi.fn().mockReturnValue(undefined),
  clearStatistics: vi.fn().mockReturnValue(undefined),
  setReportingLevel: vi.fn().mockReturnValue(undefined),
  isEnabled: vi.fn().mockReturnValue(false),
};
