/**
 * QUALIA.CODE v1.1 - IErrorReportingService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IErrorReportingService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IErrorReportingService } from '../../services/interfaces/IErrorReportingService';

/**
 * High-Fidelity Mock for IErrorReportingService
 * All methods return type-safe default values
 */
export const mockErrorReportingService: IErrorReportingService = {
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  updateConfig: vi.fn().mockReturnValue(undefined),
  getStatistics: vi.fn().mockReturnValue({}),
  exportErrorData: vi.fn().mockReturnValue({}),
  forceFlush: vi.fn().mockResolvedValue(undefined),
  clearHistory: vi.fn().mockReturnValue(undefined),
  clearStatistics: vi.fn().mockReturnValue(undefined),
  setReportingLevel: vi.fn().mockReturnValue(undefined),
  isEnabled: vi.fn().mockReturnValue(false),
};
