/**
 * QUALIA.CODE v1.1 - IFrontendRenderingService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IFrontendRenderingService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IFrontendRenderingService } from '../../services/interfaces/IFrontendRenderingService';

/**
 * High-Fidelity Mock for IFrontendRenderingService
 * All methods return type-safe default values
 */
export const mockFrontendRenderingService: IFrontendRenderingService = {
  initializeRenderer: vi.fn().mockResolvedValue(undefined),
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  updateParticleBuffer: vi.fn().mockReturnValue(undefined),
  resize: vi.fn().mockReturnValue(undefined),
  getStats: vi.fn().mockReturnValue({}),
  dispose: vi.fn().mockReturnValue(undefined),
};
