/**
 * QUALIA.CODE v1.1 - IGameControllerService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IGameControllerService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IGameControllerService } from '../../services/interfaces/IGameControllerService';

/**
 * High-Fidelity Mock for IGameControllerService
 * All methods return type-safe default values
 */
export const mockGameControllerService: IGameControllerService = {
  startGame: vi.fn().mockResolvedValue(undefined),
  pauseGame: vi.fn().mockReturnValue(undefined),
  resumeGame: vi.fn().mockReturnValue(undefined),
  resetGame: vi.fn().mockReturnValue(undefined),
  getGameState: vi.fn().mockReturnValue({}),
  isPlaying: vi.fn().mockReturnValue(false),
  isPaused: vi.fn().mockReturnValue(false),
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
};
