/**
 * QUALIA.CODE v1.1 - IGameplayMechanicsService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IGameplayMechanicsService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IGameplayMechanicsService } from '../../services/interfaces/IGameplayMechanicsService';

/**
 * High-Fidelity Mock for IGameplayMechanicsService
 * All methods return type-safe default values
 */
export const mockGameplayMechanicsService: IGameplayMechanicsService = {
  calculateNoteAccuracy: vi.fn().mockReturnValue(0),
  calculateScoreForHit: vi.fn().mockReturnValue({}),
  determineHitResult: vi.fn().mockReturnValue({}),
  getTimingWindows: vi.fn().mockReturnValue({}),
  findNearestNote: vi.fn().mockReturnValue({}),
  calculateComboMultiplier: vi.fn().mockReturnValue(0),
};
