/**
 * QUALIA.CODE v1.1 - IGameInputControllerService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IGameInputControllerService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IGameInputControllerService } from '../../services/interfaces/IGameInputControllerService';

/**
 * High-Fidelity Mock for IGameInputControllerService
 * All methods return type-safe default values
 */
export const mockGameInputControllerService: IGameInputControllerService = {
  initializeInputHandling: vi.fn().mockReturnValue(undefined),
  cleanupInputHandling: vi.fn().mockReturnValue(undefined),
  processPauseGame: vi.fn().mockReturnValue(undefined),
};
