/**
 * QUALIA.CODE v1.1 - IInputStateService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IInputStateService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IInputStateService } from '../../services/interfaces/IInputStateService';

/**
 * High-Fidelity Mock for IInputStateService
 * All methods return type-safe default values
 */
export const mockInputStateService: IInputStateService = {
  pressKey: vi.fn().mockReturnValue(undefined),
  releaseKey: vi.fn().mockReturnValue(undefined),
  isKeyPressed: vi.fn().mockReturnValue(false),
  // HIGH-FIDELITY: Return valid direction vector with x, y coordinates
  getDirectionVector: vi.fn().mockReturnValue({ x: 0, y: 0 }),
  wasActionJustPressed: vi.fn().mockReturnValue(false),
};
