/**
 * QUALIA.CODE v1.1 - INotificationService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for INotificationService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { INotificationService } from '../../services/interfaces/INotificationService';

/**
 * High-Fidelity Mock for INotificationService
 * All methods return type-safe default values
 */
export const mockNotificationService: INotificationService = {
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  dismissNotification: vi.fn().mockReturnValue(undefined),
  clearAllNotifications: vi.fn().mockReturnValue(undefined),
  hideNotification: vi.fn().mockReturnValue(undefined),
  hideAllNotifications: vi.fn().mockReturnValue(undefined),
  getActiveNotifications: vi.fn().mockReturnValue({}),
  updateConfig: vi.fn().mockReturnValue(undefined),
  getStatistics: vi.fn().mockReturnValue({}),
  getStatus: vi.fn().mockReturnValue({}),
  exportNotificationData: vi.fn().mockReturnValue({}),
  isEnabled: vi.fn().mockReturnValue(false),
};
