/**
 * QUALIA.CODE v1.1 - INotificationService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for INotificationService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { INotificationService } from '../../services/interfaces/INotificationService';

/**
 * High-Fidelity Mock for INotificationService
 * All methods return type-safe default values
 */
export const mockNotificationService: INotificationService = {
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  showNotification: vi.fn().mockReturnValue(''),
  show: vi.fn().mockReturnValue(''),
  dismissNotification: vi.fn().mockReturnValue(undefined),
  clearAllNotifications: vi.fn().mockReturnValue(undefined),
  hideNotification: vi.fn().mockReturnValue(undefined),
  hideAllNotifications: vi.fn().mockReturnValue(undefined),
  getActiveNotifications: vi.fn().mockReturnValue([]),
  updateConfig: vi.fn().mockReturnValue(undefined),
  getStatistics: vi.fn().mockReturnValue({
    totalNotifications: 0,
    activeNotifications: 0,
    dismissedNotifications: 0,
    averageDuration: 0,
  }),
  getStatus: vi.fn().mockReturnValue({
    isRunning: false,
    queueSize: 0,
  }),
  exportNotificationData: vi.fn().mockReturnValue({
    statistics: {
      totalNotifications: 0,
      activeNotifications: 0,
      dismissedNotifications: 0,
      averageDuration: 0,
    },
    activeNotifications: [],
    history: [],
    exportTimestamp: new Date(),
    version: '1.0.0',
  }),
  isEnabled: vi.fn().mockReturnValue(false),
};
