/**
 * QUALIA.CODE v1.1 - IPostProcessingService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IPostProcessingService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IPostProcessingService } from '../../services/interfaces/IPostProcessingService';

/**
 * High-Fidelity Mock for IPostProcessingService
 * All methods return type-safe default values
 */
export const mockPostProcessingService: IPostProcessingService = {
  initialize: vi.fn().mockResolvedValue(undefined),
  render: vi.fn().mockReturnValue(undefined),
  resize: vi.fn().mockReturnValue(undefined),
  dispose: vi.fn().mockReturnValue(undefined),
  getStats: vi.fn().mockReturnValue({}),
};
