/**
 * QUALIA.CODE v1.1 - IRhythmicMovementController Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IRhythmicMovementController
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IRhythmicMovementController } from '../../services/interfaces/IRhythmicMovementController';

/**
 * High-Fidelity Mock for IRhythmicMovementController
 * All methods return type-safe default values
 */
export const mockRhythmicMovementController: IRhythmicMovementController = {
  start: vi.fn().mockReturnValue(undefined),
  stop: vi.fn().mockReturnValue(undefined),
  updateMovement: vi.fn().mockReturnValue(undefined),
  setIntensity: vi.fn().mockReturnValue(undefined),
  getIntensity: vi.fn().mockReturnValue(0),
  isRunning: vi.fn().mockReturnValue(false),
  updateConfig: vi.fn().mockReturnValue(undefined),
  getStats: vi.fn().mockReturnValue({
    isRunning: false,
    currentIntensity: 0,
    updatesPerformed: 0,
    averageUpdateTime: 0,
  }),
  getCurrentBPM: vi.fn().mockReturnValue(0),
  getCurrentBeat: vi.fn().mockReturnValue(0),
  isPlaying: vi.fn().mockReturnValue(false),
};
