/**
 * QUALIA.CODE v1.1 - IShaderLoaderService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IShaderLoaderService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IShaderLoaderService } from '../../services/interfaces/IShaderLoaderService';

/**
 * High-Fidelity Mock for IShaderLoaderService
 * All methods return type-safe default values
 */
export const mockShaderLoaderService: IShaderLoaderService = {
  load: vi.fn().mockResolvedValue(''),
};
