/**
 * QUALIA.CODE v1.1 - IStateStreamingService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IStateStreamingService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IStateStreamingService } from '../../services/interfaces/IStateStreamingService';

/**
 * High-Fidelity Mock for IStateStreamingService
 * All methods return type-safe default values
 */
export const mockStateStreamingService: IStateStreamingService = {
  start: vi.fn().mockResolvedValue(undefined),
  connect: vi.fn().mockResolvedValue(undefined),
  disconnect: vi.fn().mockResolvedValue(undefined),
  getConnectionStatus: vi.fn().mockReturnValue({}),
};
