/**
 * QUALIA.CODE v1.1 - IStreamingVideoService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IStreamingVideoService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IStreamingVideoService } from '../../services/interfaces/IStreamingVideoService';

/**
 * High-Fidelity Mock for IStreamingVideoService
 * All methods return type-safe default values
 */
export const mockStreamingVideoService: IStreamingVideoService = {
  connect: vi.fn().mockResolvedValue(undefined),
  disconnect: vi.fn().mockReturnValue(undefined),
  unsubscribeFromFrames: vi.fn().mockReturnValue(undefined),
  getConnectionStatus: vi.fn().mockReturnValue({}),
  getStatistics: vi.fn().mockReturnValue({}),
  requestQualityChange: vi.fn().mockReturnValue(undefined),
  requestFpsChange: vi.fn().mockReturnValue(undefined),
  ping: vi.fn().mockResolvedValue(0),
};
