/**
 * QUALIA.CODE v1.1 - ISubtitleService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for ISubtitleService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { ISubtitleService } from '../../services/interfaces/ISubtitleService';

/**
 * High-Fidelity Mock for ISubtitleService
 * All methods return type-safe default values
 */
export const mockSubtitleService: ISubtitleService = {
  getCurrentLyric: vi.fn().mockReturnValue({}),
  shouldDisplayLyric: vi.fn().mockReturnValue(false),
  getDisplayDuration: vi.fn().mockReturnValue(0),
};
