/**
 * QUALIA.CODE v1.1 - ITimerProvider Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for ITimerProvider
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { ITimerProvider } from '../../services/interfaces/ITimerProvider';

/**
 * High-Fidelity Mock for ITimerProvider
 * All methods return type-safe default values
 */
export const mockTimerProvider: ITimerProvider = {
  clearTimeout: vi.fn().mockReturnValue(undefined),
  clearInterval: vi.fn().mockReturnValue(undefined),
  cancelAnimationFrame: vi.fn().mockReturnValue(undefined),
  performanceNow: vi.fn().mockReturnValue(0),
  now: vi.fn().mockReturnValue(0),
  getCurrentDate: vi.fn().mockReturnValue({}),
};
