/**
 * QUALIA.CODE v1.1 - IViewLogicService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IViewLogicService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IViewLogicService } from '../../services/interfaces/IViewLogicService';

/**
 * High-Fidelity Mock for IViewLogicService
 * All methods return type-safe default values
 */
export const mockViewLogicService: IViewLogicService = {
  getBossVisuals: vi.fn().mockReturnValue({}),
  getPlayerVisuals: vi.fn().mockReturnValue({}),
  getQualiaFieldVisuals: vi.fn().mockReturnValue({}),
  getQualiaFieldParticles: vi.fn().mockReturnValue({}),
  getMusicalNoteVisuals: vi.fn().mockReturnValue({}),
  getGridVisuals: vi.fn().mockReturnValue({}),
};
