/**
 * QUALIA.CODE v1.1 - IViewLogicService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IViewLogicService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IViewLogicService } from '../../services/interfaces/IViewLogicService';

/**
 * High-Fidelity Mock for IViewLogicService
 * All methods return type-safe default values
 * QUALIA.CODE v2.0: Updated with new calculation and builder methods
 */
export const mockViewLogicService: IViewLogicService = {
  getBossVisuals: vi.fn().mockReturnValue({}),
  getPlayerVisuals: vi.fn().mockReturnValue({}),
  getQualiaFieldVisuals: vi.fn().mockReturnValue({}),
  getQualiaFieldParticles: vi.fn().mockReturnValue([]),
  getMusicalNoteVisuals: vi.fn().mockReturnValue([]),
  getGridVisuals: vi.fn().mockReturnValue({}),
  
  // QUALIA.CODE v2.0: New calculation methods
  calculateAccuracy: vi.fn().mockReturnValue(0),
  calculateBossPowerLevel: vi.fn().mockReturnValue(0),
  calculateBossPhase: vi.fn().mockReturnValue(1),
  
  // QUALIA.CODE v2.0: New builder methods
  buildPlayerRenderProps: vi.fn().mockReturnValue({
    player: {
      id: 'player_1',
      name: 'Test Player',
      position: [0, 0, 0],
      velocity: [0, 0, 0],
      health: 100,
      power_level: 100,
      consciousness_level: 0,
      qualia_state: {
        emotional_valence: 0,
        arousal: 0,
        coherence: 0
      }
    },
    performance: {
      accuracy: 0,
      rhythm_score: 0,
      combo_multiplier: 0,
      rhythm_sync: 0,
      qualia_coherence: 0
    }
  }),
  
  buildBossRenderProps: vi.fn().mockReturnValue({
    id: 'boss_1',
    name: 'Test Boss',
    position: [0, 0, 0],
    power_level: 0,
    phase: 1,
    stress_level: 0,
    qualia_state: {
      consciousness_density: 0,
      emotional_valence: 0,
      arousal: 0,
      coherence: 0
    }
  }),
  
  buildQualiaFieldRenderProps: vi.fn().mockReturnValue({
    qualiaState: {
      intensity: 0,
      precision: 0,
      aggression: 0,
      flow: 0,
      chaos: 0,
      recovery: 0,
      transcendence: 0
    },
    musicData: {
      tempo: 120,
      beat_position: 0,
      intensity: 0,
      frequency_bands: [0, 0, 0, 0],
      order_influence: 0,
      chaos_influence: 0,
      emotional_valence: 0,
      harmony: 0
    }
  }),
  
  // PHASE 5.6: Avatar visual methods
  getPlayerAvatarVisuals: vi.fn().mockReturnValue({
    position: { x: 0, y: 0, z: 0 },
    scale: 1.0,
    shapeParameters: { x: 0.5, y: 0.5, z: 0.5 },
    baseColor: { r: 0.3, g: 0.5, b: 0.8 },
    emissive: 0.5,
    useFractal: false
  }),
  
  getBossAvatarVisuals: vi.fn().mockReturnValue({
    position: { x: 0, y: 0, z: 5 },
    scale: 1.5,
    shapeParameters: { x: 0.7, y: 0.7, z: 0.7 },
    baseColor: { r: 0.8, g: 0.3, b: 0.3 },
    emissive: 0.7,
    timeOffset: 0
  }),
  
  getMandelbulbVisuals: vi.fn().mockReturnValue({
    position: { x: 0, y: 0, z: 0 },
    scale: 1.2,
    iterations: 8,
    power: 8.0,
    colorGradient: {
      inner: { r: 1.0, g: 0.84, b: 0.0 },
      outer: { r: 1.0, g: 0.5, b: 0.2 }
    },
    rimLightIntensity: 0.8,
    glowRadius: 2.0
  })
};
