/**
 * QUALIA.CODE v1.1 - IWebAudioAPIService Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IWebAudioAPIService
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IWebAudioAPIService } from '../../services/interfaces/IWebAudioAPIService';

/**
 * High-Fidelity Mock for IWebAudioAPIService
 * All methods return type-safe default values
 */
export const mockWebAudioAPIService: IWebAudioAPIService = {
  getAudioContext: vi.fn().mockReturnValue({}),
  playTone: vi.fn().mockReturnValue(undefined),
  playTone: vi.fn().mockReturnValue(undefined),
  startContext: vi.fn().mockResolvedValue(undefined),
};
