/**
 * QUALIA.CODE v1.1 - IWebSocketFactory Mock
 * HIGH-FIDELITY MOCK: Contract-compliant mock for IWebSocketFactory
 * 
 * COMPLIANCE: QUALIA.CODE Section 10.3.1 - High-Fidelity Mocking Standard
 * GENERATED: This file was auto-generated by ARCHITECTURAL DIRECTIVE 003
 */

import { vi } from 'vitest';
import type { IWebSocketFactory } from '../../services/interfaces/IWebSocketFactory';

/**
 * High-Fidelity Mock for IWebSocketFactory
 * All methods return type-safe default values
 */
export const mockWebSocketFactory: IWebSocketFactory = {
  create: vi.fn().mockReturnValue({}),
};
