// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: AudioLayer.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:48Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Audio mixing layer
 */
export interface AudioLayer {
  /**
   * Unique layer identifier
   */
  id: string;
  /**
   * Human-readable layer name
   */
  name: string;
  /**
   * Layer category
   */
  type: "music" | "sfx" | "ambient" | "voice" | "ui";
  /**
   * Layer master volume (0-1)
   */
  volume: number;
  /**
   * Whether layer is muted
   */
  muted: boolean;
  /**
   * Whether layer is soloed (only this plays)
   */
  solo: boolean;
  /**
   * Currently active audio sources in this layer
   */
  activeSources: {
    sourceId: string;
    audioClipId: string;
    startTime: number;
    volume: number;
    isLooping: boolean;
    [k: string]: unknown;
  }[];
  /**
   * Audio effects chain for this layer
   */
  effects: {
    effectId: string;
    type: "compressor" | "eq" | "reverb" | "delay" | "limiter" | "distortion";
    enabled: boolean;
    parameters?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Audio routing configuration
   */
  routing?: {
    /**
     * Output bus identifier
     */
    outputBus?: string;
    /**
     * Send levels to auxiliary buses
     */
    sendLevels?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  /**
   * How Qualia state modulates this layer
   */
  qualiaModulation?: {
    volumeByIntensity?: boolean;
    filterByTranscendence?: boolean;
    pitchByChaos?: boolean;
    [k: string]: unknown;
  };
}
