// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: AudioEvent.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:48Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Audio system event
 */
export interface AudioEvent {
  /**
   * Unique event identifier
   */
  id: string;
  /**
   * Audio event type
   */
  type:
    | "play_sfx"
    | "stop_sfx"
    | "play_music"
    | "stop_music"
    | "crossfade"
    | "volume_change"
    | "pitch_shift"
    | "apply_filter"
    | "trigger_stinger"
    | "sync_beat";
  /**
   * Event timestamp
   */
  timestamp: number;
  /**
   * Audio clip identifier
   */
  audioClipId?: string;
  /**
   * Target audio layer
   */
  layerId?: string;
  /**
   * Audio playback parameters
   */
  parameters?: {
    volume?: number;
    pitch?: number;
    pan?: number;
    fadeInSec?: number;
    fadeOutSec?: number;
    loop?: boolean;
    priority?: number;
    [k: string]: unknown;
  };
  /**
   * Audio filter settings
   */
  filterSettings?: {
    type?: "lowpass" | "highpass" | "bandpass" | "reverb" | "delay" | "distortion";
    frequency?: number;
    resonance?: number;
    wetDryMix?: number;
    [k: string]: unknown;
  };
  /**
   * 3D spatial audio data
   */
  spatialData?: {
    position?: {
      x: number;
      y: number;
      z: number;
      [k: string]: unknown;
    };
    maxDistance?: number;
    rolloffFactor?: number;
    [k: string]: unknown;
  };
  /**
   * Conditions for triggering this event
   */
  triggerCondition?: {
    qualiaThreshold?: number;
    comboBased?: boolean;
    beatSynced?: boolean;
    [k: string]: unknown;
  };
}
