// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: BossState.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:48Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Boss state data structure for Qualia Tempo
 */
export interface BossState {
  /**
   * Unique identifier for the boss
   */
  id: string;
  /**
   * Display name of the boss
   */
  name: string;
  position: {
    x: number;
    y: number;
  };
  /**
   * Current health
   */
  health: number;
  /**
   * Maximum health
   */
  maxHealth: number;
  /**
   * Current combat phase
   */
  currentPhase: number;
  /**
   * IDs of currently active attack patterns
   */
  activePatterns: string[];
  /**
   * Active boss buffs
   */
  buffs: string[];
  /**
   * Active boss debuffs
   */
  debuffs: string[];
  /**
   * Current aggression level influenced by tempo and volume
   */
  currentAggressionLevel: number;
}
