// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: CombatState.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-08T05:40:15Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Overall combat state structure - complete game state for rendering
 */
export interface CombatState {
  /**
   * Current game state
   */
  gameState: "idle" | "playing" | "paused" | "game_over";
  /**
   * Whether combat is currently active
   */
  isActive: boolean;
  /**
   * Current phase of the combat
   */
  currentPhase: number;
  /**
   * Elapsed time since combat start (seconds)
   */
  elapsedTime: number;
  /**
   * Progress through the song (0-1)
   */
  songProgress: number;
  /**
   * Player entity state
   */
  player: {
    /**
     * Player health (0-100)
     */
    health: number;
    /**
     * Player 3D position
     */
    position: {
      x: number;
      y: number;
      z: number;
      [k: string]: unknown;
    };
    /**
     * Current player score
     */
    score: number;
    /**
     * Current combo count
     */
    combo: number;
    /**
     * Maximum combo achieved
     */
    maxCombo: number;
    /**
     * Player movement speed
     */
    moveSpeed: number;
    /**
     * Whether player is temporarily invulnerable
     */
    isInvulnerable: boolean;
    [k: string]: unknown;
  };
  /**
   * Boss entity state
   */
  boss: {
    /**
     * Boss health (0-100)
     */
    health: number;
    /**
     * Boss 3D position
     */
    position: {
      x: number;
      y: number;
      z: number;
      [k: string]: unknown;
    };
    /**
     * Current boss phase (affects appearance and behavior)
     */
    currentPhase: number;
    /**
     * Current attack pattern name
     */
    attackPattern: string;
    /**
     * Whether boss can currently take damage
     */
    isVulnerable: boolean;
    /**
     * Health threshold for next phase transition
     */
    nextPhaseThreshold: number;
    [k: string]: unknown;
  };
  /**
   * IDs of active visual effects
   */
  activeEffects: string[];
  /**
   * IDs of active environment effects
   */
  environmentEffects: string[];
  /**
   * Recent history of Qualia events
   */
  qualiaEventHistory: {
    id: string;
    timestamp: number;
    position: {
      x: number;
      y: number;
      [k: string]: unknown;
    };
    value: number;
    [k: string]: unknown;
  }[];
}
