// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: CombatState.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:49Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Overall combat state structure
 */
export interface CombatState {
  /**
   * Whether combat is currently active
   */
  isActive: boolean;
  /**
   * Current phase of the combat
   */
  currentPhase: number;
  /**
   * Elapsed time since combat start (seconds)
   */
  elapsedTime: number;
  /**
   * Progress through the song (0-1)
   */
  songProgress: number;
  /**
   * IDs of active visual effects
   */
  activeEffects: string[];
  /**
   * IDs of active environment effects
   */
  environmentEffects: string[];
  /**
   * Recent history of Qualia events
   */
  qualiaEventHistory: {
    id: string;
    timestamp: number;
    position: {
      x: number;
      y: number;
      [k: string]: unknown;
    };
    value: number;
    [k: string]: unknown;
  }[];
}
