// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: CombatData.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-01T07:22:26Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Combat scenario data structure for Qualia Tempo
 */
export interface CombatData {
  /**
   * Unique identifier for the combat scenario
   */
  id: string;
  /**
   * Display title of the combat scenario
   */
  title: string;
  /**
   * Artist name
   */
  artist: string;
  /**
   * Path to audio file (mp3, ogg)
   */
  audioPath: string;
  /**
   * Beats per minute of the track
   */
  bpm: number;
  /**
   * Duration of the track in seconds
   */
  duration: number;
  /**
   * Array of all notes in the map
   */
  noteMap: NoteData[];
  /**
   * Array of all lyrics in the song
   */
  lyrics: LyricData[];
}
export interface NoteData {
  /**
   * Unique identifier for the note
   */
  id: string;
  /**
   * Time in seconds from song start
   */
  timestamp: number;
  position: {
    /**
     * X position on stage
     */
    x: number;
    /**
     * Y position on stage
     */
    y: number;
  };
  /**
   * Duration the note remains active
   */
  duration: number;
  /**
   * Qualia signature for the note
   */
  qualia_signature: string;
  /**
   * Lifecycle state of the note
   */
  state: "active" | "hit" | "missed";
}
export interface LyricData {
  /**
   * Time in seconds from song start
   */
  timestamp: number;
  /**
   * Lyric text content
   */
  text: string;
}
