// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: IActiveEffect.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:49Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Active visual effect instance
 */
export interface IActiveEffect {
  /**
   * Unique instance identifier
   */
  id: string;
  /**
   * Type of visual effect
   */
  effectType:
    | "particle_burst"
    | "trail"
    | "aura"
    | "screen_shake"
    | "color_shift"
    | "distortion"
    | "bloom_pulse"
    | "god_rays"
    | "reaction_diffusion"
    | "sdf_morph";
  /**
   * Effect start timestamp
   */
  startTime: number;
  /**
   * Effect duration (seconds)
   */
  durationSec: number;
  /**
   * 3D position in world space
   */
  position: {
    x: number;
    y: number;
    z: number;
    [k: string]: unknown;
  };
  /**
   * Effect intensity (0-1)
   */
  intensity: number;
  /**
   * RGBA color
   */
  color: {
    r: number;
    g: number;
    b: number;
    a: number;
    [k: string]: unknown;
  };
  /**
   * Effect scale multiplier
   */
  scale: number;
  /**
   * Fade in duration (seconds)
   */
  fadeInSec?: number;
  /**
   * Fade out duration (seconds)
   */
  fadeOutSec?: number;
  /**
   * Optional entity ID to attach effect to
   */
  attachedToEntity?: string;
  /**
   * Effect-specific parameters
   */
  customParameters?: {
    [k: string]: unknown;
  };
}
