// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: IEnvironmentEffect.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:49Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Environmental effect affecting gameplay area
 */
export interface IEnvironmentEffect {
  /**
   * Unique effect identifier
   */
  id: string;
  /**
   * Environment effect type
   */
  type:
    | "gravity_shift"
    | "time_dilation"
    | "color_filter"
    | "ambient_particles"
    | "lighting_change"
    | "fog"
    | "wind"
    | "barrier";
  /**
   * Effect start timestamp
   */
  startTime: number;
  /**
   * Effect duration (seconds, -1 for permanent)
   */
  durationSec: number;
  affectedArea: {
    shape: "circle" | "rectangle" | "global";
    center?: {
      x?: number;
      y?: number;
      [k: string]: unknown;
    };
    radius?: number;
    width?: number;
    height?: number;
    [k: string]: unknown;
  };
  /**
   * Effect intensity (0-1)
   */
  intensity: number;
  /**
   * Gameplay parameter modifiers
   */
  gameplayModifiers?: {
    playerSpeedMultiplier?: number;
    gravityMultiplier?: number;
    damageMultiplier?: number;
    scoreMultiplier?: number;
    [k: string]: unknown;
  };
  /**
   * Visual rendering parameters
   */
  visualParameters?: {
    color?: {
      r?: number;
      g?: number;
      b?: number;
      a?: number;
      [k: string]: unknown;
    };
    particleDensity?: number;
    distortionAmount?: number;
    [k: string]: unknown;
  };
  /**
   * Optional Qualia thresholds that trigger this effect
   */
  triggeredByQualiaState?: {
    /**
     * Transcendence threshold
     */
    transcendence?: number;
    /**
     * Chaos threshold
     */
    chaos?: number;
    [k: string]: unknown;
  };
}
