// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: IGameSettings.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:50Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Game settings configuration
 */
export interface IGameSettings {
  audio: {
    masterVolume: number;
    musicVolume: number;
    sfxVolume: number;
    /**
     * Audio calibration offset (milliseconds)
     */
    audioOffsetMs: number;
    [k: string]: unknown;
  };
  gameplay: {
    /**
     * Timing windows for hit accuracy (milliseconds)
     */
    timingWindowMs: {
      perfect: number;
      good: number;
      ok: number;
      [k: string]: unknown;
    };
    /**
     * Enable autoplay mode
     */
    autoplay: boolean;
    /**
     * Enable practice mode
     */
    practiceMode: boolean;
    /**
     * Show timing feedback
     */
    showTiming: boolean;
    [k: string]: unknown;
  };
  visual: {
    brightness: number;
    /**
     * Particle effect density
     */
    particleDensity: "low" | "medium" | "high" | "ultra";
    postProcessingEnabled: boolean;
    bloomIntensity: number;
    showHitEffects: boolean;
    showComboText: boolean;
    backgroundAnimations: boolean;
    [k: string]: unknown;
  };
  input: {
    keyBindings: {
      hitNote: string[];
      dash: string[];
      pause: string[];
      [k: string]: unknown;
    };
    mouseSensitivity: number;
    [k: string]: unknown;
  };
  accessibility: {
    colorblindMode: "none" | "protanopia" | "deuteranopia" | "tritanopia";
    screenShakeIntensity: number;
    flashingEffects: boolean;
    subtitlesEnabled: boolean;
    [k: string]: unknown;
  };
}
