// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: ILeaderboardEntry.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:50Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Leaderboard entry structure
 */
export interface ILeaderboardEntry {
  /**
   * Player rank position
   */
  rank: number;
  /**
   * Unique player identifier
   */
  playerId: string;
  /**
   * Player display name
   */
  playerName: string;
  /**
   * Total score
   */
  score: number;
  /**
   * Song identifier
   */
  songId: string;
  /**
   * Difficulty level played
   */
  difficulty: "easy" | "medium" | "hard" | "expert";
  /**
   * Maximum combo achieved
   */
  maxCombo: number;
  /**
   * Hit accuracy (0-1)
   */
  accuracy: number;
  /**
   * Unix timestamp of the run
   */
  timestamp: number;
  /**
   * Final Qualia state at end of run
   */
  qualiaSnapshot: {
    intensity?: number;
    precision?: number;
    aggression?: number;
    flow?: number;
    chaos?: number;
    recovery?: number;
    transcendence?: number;
    [k: string]: unknown;
  };
  /**
   * Optional URL to replay data
   */
  replayDataUrl?: string;
}
