// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: IMusicalInputAnalysis.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:50Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Analysis of player input from musical perspective
 */
export interface IMusicalInputAnalysis {
  /**
   * Analysis timestamp
   */
  timestamp: number;
  /**
   * Last N inputs for analysis window
   */
  recentInputs: {
    action: "hit" | "dash" | "miss";
    timestamp: number;
    /**
     * Offset from beat (ms)
     */
    timingOffset: number;
    accuracy: "perfect" | "good" | "ok" | "miss";
    [k: string]: unknown;
  }[];
  /**
   * How consistently player hits on beat (0-1)
   */
  rhythmicConsistency: number;
  /**
   * Detected rhythmic pattern
   */
  detectedPattern: "none" | "steady" | "syncopated" | "polyrhythmic" | "chaotic";
  /**
   * Alignment with song's harmony (0-1)
   */
  harmonicAlignment: number;
  /**
   * How well player completes musical phrases (0-1)
   */
  phraseCompletion: number;
  /**
   * Variation in input intensity (0-1)
   */
  dynamicRange: number;
  /**
   * Suggested Qualia adjustments based on analysis
   */
  suggestedQualiaShift: {
    intensity?: number;
    precision?: number;
    aggression?: number;
    flow?: number;
    chaos?: number;
    [k: string]: unknown;
  };
}
