// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: ISongData.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-06T17:34:50Z

 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Song metadata and structure
 */
export interface ISongData {
  /**
   * Unique song identifier
   */
  id: string;
  /**
   * Song title
   */
  title: string;
  /**
   * Song artist
   */
  artist: string;
  /**
   * Beats per minute
   */
  bpm: number;
  /**
   * Total song duration (seconds)
   */
  durationSec: number;
  /**
   * Path to audio file
   */
  audioFilePath: string;
  /**
   * Time signature (e.g., 4/4, 3/4)
   */
  timeSignature: {
    numerator: number;
    denominator: number;
    [k: string]: unknown;
  };
  /**
   * Musical key (e.g., 'C major', 'D minor')
   */
  key?: string;
  /**
   * Song sections
   */
  sections?: {
    /**
     * Section type
     */
    name: "intro" | "verse" | "chorus" | "bridge" | "outro";
    /**
     * Start time (seconds)
     */
    startTimeSec: number;
    /**
     * End time (seconds)
     */
    endTimeSec: number;
    [k: string]: unknown;
  }[];
  /**
   * Precise beat timestamps
   */
  beatMap: {
    timestamp: number;
    beatNumber: number;
    barNumber: number;
    isDownbeat: boolean;
    [k: string]: unknown;
  }[];
  /**
   * Song difficulty tier
   */
  difficulty: "easy" | "medium" | "hard" | "expert";
  /**
   * Timestamp for preview start (seconds)
   */
  previewStartSec?: number;
}
