// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: MusicalComboData.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-08T05:40:17Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Musical combo definitions - sequences of hits that create harmonic effects
 */
export interface MusicalComboData {
  /**
   * Unique combo identifier
   */
  id: string;
  /**
   * Human-readable combo name
   */
  name: string;
  /**
   * Sequence of actions forming the combo
   *
   * @minItems 2
   */
  sequence: [
    {
      /**
       * Action type
       */
      action: "hit" | "dash" | "parry" | "sustain";
      /**
       * Timing requirement
       */
      timing: "exact" | "early" | "late" | "any";
      /**
       * Maximum delay from previous action (milliseconds)
       */
      maxDelayMs?: number;
      [k: string]: unknown;
    },
    {
      /**
       * Action type
       */
      action: "hit" | "dash" | "parry" | "sustain";
      /**
       * Timing requirement
       */
      timing: "exact" | "early" | "late" | "any";
      /**
       * Maximum delay from previous action (milliseconds)
       */
      maxDelayMs?: number;
      [k: string]: unknown;
    },
    ...{
      /**
       * Action type
       */
      action: "hit" | "dash" | "parry" | "sustain";
      /**
       * Timing requirement
       */
      timing: "exact" | "early" | "late" | "any";
      /**
       * Maximum delay from previous action (milliseconds)
       */
      maxDelayMs?: number;
      [k: string]: unknown;
    }[]
  ];
  /**
   * Score multiplier when combo completed
   */
  bonusMultiplier: number;
  /**
   * Qualia state modifiers applied on completion
   */
  qualiaModifiers: {
    intensity?: number;
    precision?: number;
    aggression?: number;
    flow?: number;
    chaos?: number;
    recovery?: number;
    transcendence?: number;
    [k: string]: unknown;
  };
  /**
   * ID of visual effect to trigger
   */
  visualEffectId?: string;
  /**
   * ID of audio effect to trigger
   */
  audioEffectId?: string;
  /**
   * Combo difficulty tier
   */
  difficulty: "easy" | "medium" | "hard" | "expert";
}
