// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: OptimizedParticle.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-02T05:09:03Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GOLD.CODE: Memory-optimized particle structure with precision-matched types. Achieves 26% memory reduction (84→62 bytes per particle) through structured NumPy array with uint8 colors and float16 scalars.
 */
export interface OptimizedParticle {
  /**
   * 3D position vector in world space (float32 for precision)
   *
   * @minItems 3
   * @maxItems 3
   */
  position: [number, number, number];
  /**
   * 3D velocity vector (float32 for physics accuracy)
   *
   * @minItems 3
   * @maxItems 3
   */
  velocity: [number, number, number];
  /**
   * 3D acceleration vector (float32 for physics calculations)
   *
   * @minItems 3
   * @maxItems 3
   */
  acceleration: [number, number, number];
  /**
   * Accumulated forces for integration (float32)
   *
   * @minItems 3
   * @maxItems 3
   */
  force_accumulator: [number, number, number];
  /**
   * RGBA color with uint8 components (0-255 range). 75% memory savings vs float32.
   *
   * @minItems 4
   * @maxItems 4
   */
  color: [number, number, number, number];
  /**
   * Remaining lifetime in seconds (float16). 50% memory savings vs float32.
   */
  lifetime: number;
  /**
   * Visual size multiplier (float16). 50% memory savings vs float32.
   */
  size: number;
  /**
   * Performance resonance factor (float16). Range: 0.0 (low) to 1.0 (high).
   */
  resonance: number;
  /**
   * Particle mass for gravitational physics (float16). 50% memory savings vs float32.
   */
  mass: number;
  /**
   * Electromagnetic charge for force field interactions (float16). Can be negative.
   */
  charge: number;
}
