// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: PatternData.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-08T05:40:18Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Boss attack pattern definition
 */
export interface PatternData {
  /**
   * Unique pattern identifier
   */
  id: string;
  /**
   * Human-readable pattern name
   */
  name: string;
  /**
   * Attack pattern type
   */
  type: "projectile" | "area" | "melee" | "summon" | "buff";
  /**
   * Boss phases where this pattern can appear
   */
  phases: number[];
  /**
   * Notes/projectiles in this pattern
   */
  notes: {
    /**
     * Time offset from pattern start (seconds)
     */
    timestamp: number;
    position: {
      x: number;
      y: number;
      [k: string]: unknown;
    };
    velocity?: {
      x: number;
      y: number;
      [k: string]: unknown;
    };
    damage: number;
    visualData?: {
      color?: string;
      size?: number;
      shape?: "circle" | "square" | "triangle" | "custom";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Total pattern duration (seconds)
   */
  durationSec: number;
  /**
   * Cooldown before pattern can repeat (seconds)
   */
  cooldownSec: number;
  /**
   * Qualia thresholds required to trigger this pattern
   */
  requiredQualiaThreshold?: {
    aggression?: number;
    chaos?: number;
    [k: string]: unknown;
  };
}
