// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: PlayerState.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-09-17T20:04:26Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Player state data structure
 */
export interface PlayerState {
  position: {
    /**
     * X coordinate
     */
    x: number;
    /**
     * Y coordinate
     */
    y: number;
  };
  /**
   * Player health (0-100)
   */
  health: number;
  /**
   * Current combo count
   */
  combo: number;
  /**
   * Current score
   */
  score: number;
  /**
   * Whether player is currently moving
   */
  isMoving: boolean;
  /**
   * Timestamp of last rhythm hit
   */
  lastRhythmHit: number;
}
