// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: PlayerState.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-10-08T05:40:18Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Player state data structure
 */
export interface PlayerState {
  position: {
    /**
     * X coordinate
     */
    x: number;
    /**
     * Y coordinate
     */
    y: number;
  };
  /**
   * Player health (0-100)
   */
  health: number;
  /**
   * Current combo count
   */
  combo: number;
  /**
   * Current score
   */
  score: number;
  /**
   * Whether player is currently moving
   */
  isMoving: boolean;
  /**
   * Timestamp of last rhythm hit
   */
  lastRhythmHit: number;
  /**
   * Player velocity vector
   */
  velocity: {
    x: number;
    y: number;
    [k: string]: unknown;
  };
  /**
   * Player ability states
   */
  abilities: {
    dash: {
      isReady: boolean;
      cooldownRemaining: number;
      [k: string]: unknown;
    };
    parry: {
      isReady: boolean;
      cooldownRemaining: number;
      [k: string]: unknown;
    };
    ultimate: {
      isActive: boolean;
      charge: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Active buffs
   */
  buffs: {
    id: string;
    name: string;
    durationRemaining: number;
    [k: string]: unknown;
  }[];
  /**
   * Active debuffs
   */
  debuffs: {
    id: string;
    name: string;
    durationRemaining: number;
    [k: string]: unknown;
  }[];
}
