// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: QualiaState.json
// Run `scripts/generate_contracts.sh` to regenerate
// Last generated: 2025-09-30T21:02:28Z

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Central data structure representing player mastery in Qualia Tempo
 */
export interface QualiaState {
  /**
   * Overall energy level (0-1)
   */
  intensity: number;
  /**
   * Accuracy streaks (0-1)
   */
  precision: number;
  /**
   * Fast Forward usage (0-1)
   */
  aggression: number;
  /**
   * Rhythmic consistency (0-1)
   */
  flow: number;
  /**
   * Rhythm failures (0-1)
   */
  chaos: number;
  /**
   * Rewind usage (0-1)
   */
  recovery: number;
  /**
   * Ultimate mode (0-1)
   */
  transcendence: number;
}
