# @generated DO NOT EDIT
# GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from JSON schemas in /shared_contracts
# Run `scripts/generate_contracts.sh` to regenerate

from __future__ import annotations
from pydantic import BaseModel, Field, Extra, ConfigDict
from typing import List, Optional, Annotated

from enum import Enum
from pydantic import BaseModel, ConfigDict, Field
from pydantic import BaseModel, ConfigDict, Field, RootModel
from typing import Annotated
from typing import Annotated, List

class ColorItem(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=255)]
    """
    RGBA component (uint8)
    """



class OptimizedParticle(BaseModel):
    """
    GOLD.CODE: Memory-optimized particle structure with precision-matched types. Achieves 26% memory reduction (84→62 bytes per particle) through structured NumPy array with uint8 colors and float16 scalars.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    position: Annotated[List[float], Field(max_length=3, min_length=3)]
    """
    3D position vector in world space (float32 for precision)
    """
    velocity: Annotated[List[float], Field(max_length=3, min_length=3)]
    """
    3D velocity vector (float32 for physics accuracy)
    """
    acceleration: Annotated[List[float], Field(max_length=3, min_length=3)]
    """
    3D acceleration vector (float32 for physics calculations)
    """
    force_accumulator: Annotated[List[float], Field(max_length=3, min_length=3)]
    """
    Accumulated forces for integration (float32)
    """
    color: Annotated[List[ColorItem], Field(max_length=4, min_length=4)]
    """
    RGBA color with uint8 components (0-255 range). 75% memory savings vs float32.
    """
    lifetime: Annotated[float, Field(ge=0.0)]
    """
    Remaining lifetime in seconds (float16). 50% memory savings vs float32.
    """
    size: Annotated[float, Field(ge=0.0)]
    """
    Visual size multiplier (float16). 50% memory savings vs float32.
    """
    resonance: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Performance resonance factor (float16). Range: 0.0 (low) to 1.0 (high).
    """
    mass: Annotated[float, Field(ge=0.0)]
    """
    Particle mass for gravitational physics (float16). 50% memory savings vs float32.
    """
    charge: float
    """
    Electromagnetic charge for force field interactions (float16). Can be negative.
    """


class Position(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    """
    X coordinate
    """
    y: float
    """
    Y coordinate
    """



class PlayerState(BaseModel):
    """
    Player state data structure
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    position: Position
    health: Annotated[float, Field(ge=0.0, le=100.0)]
    """
    Player health (0-100)
    """
    combo: Annotated[float, Field(ge=0.0)]
    """
    Current combo count
    """
    score: Annotated[float, Field(ge=0.0)]
    """
    Current score
    """
    isMoving: bool
    """
    Whether player is currently moving
    """
    lastRhythmHit: Annotated[float, Field(ge=0.0)]
    """
    Timestamp of last rhythm hit
    """


class QualiaState(BaseModel):
    """
    Central data structure representing player mastery in Qualia Tempo
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    intensity: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Overall energy level (0-1)
    """
    precision: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Accuracy streaks (0-1)
    """
    aggression: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Fast Forward usage (0-1)
    """
    flow: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Rhythmic consistency (0-1)
    """
    chaos: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Rhythm failures (0-1)
    """
    recovery: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Rewind usage (0-1)
    """
    transcendence: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Ultimate mode (0-1)
    """


class State(Enum):
    """
    Lifecycle state of the note
    """

    active = 'active'
    hit = 'hit'
    missed = 'missed'



class NoteData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier for the note
    """
    timestamp: Annotated[float, Field(ge=0.0)]
    """
    Time in seconds from song start
    """
    position: Position
    duration: Annotated[float, Field(ge=0.0)]
    """
    Duration the note remains active
    """
    qualia_signature: str
    """
    Qualia signature for the note
    """
    state: State
    """
    Lifecycle state of the note
    """



class LyricData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Annotated[float, Field(ge=0.0)]
    """
    Time in seconds from song start
    """
    text: str
    """
    Lyric text content
    """



class CombatData(BaseModel):
    """
    Combat scenario data structure for Qualia Tempo
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique identifier for the combat scenario
    """
    title: str
    """
    Display title of the combat scenario
    """
    artist: str
    """
    Artist name
    """
    audioPath: str
    """
    Path to audio file (mp3, ogg)
    """
    bpm: Annotated[float, Field(ge=1.0)]
    """
    Beats per minute of the track
    """
    duration: Annotated[float, Field(ge=0.0)]
    """
    Duration of the track in seconds
    """
    noteMap: List[NoteData]
    """
    Array of all notes in the map
    """
    lyrics: List[LyricData]
    """
    Array of all lyrics in the song
    """



# Additional response models for API endpoints
class QualiaUpdateResponse(BaseModel):
    """Response model for QualiaState update operations."""

    status: str
    message: str
