#!/bin/bash

# QUALIA.CODE Contract Generation Script
# Generates Pydantic models and TypeScript interfaces from JSON schemas

set -e

echo "🔄 Generating contracts from JSON schemas..."

# Configuration
CONTRACTS_DIR="$(pwd)/shared_contracts"
BACKEND_DIR="$(pwd)/qualia-tempo-prototype/backend"
FRONTEND_DIR="$(pwd)/qualia-tempo-prototype/frontend"

BACKEND_MODELS="${BACKEND_DIR}/api/models.py"
FRONTEND_CONTRACTS="${FRONTEND_DIR}/src/types/contracts.ts"

# Create directories if they don't exist
mkdir -p "$(dirname "$BACKEND_MODELS")" "$(dirname "$FRONTEND_CONTRACTS")"

# Check if required commands are installed
if ! command -v python3 &> /dev/null; then
    echo "❌ Error: python3 is not installed"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo "❌ Error: npm is not installed"
    exit 1
fi

# Check if json2ts is installed
if ! command -v json2ts &> /dev/null; then
    echo "❌ Error: json2ts is not installed. Please install it with:"
    echo "   npm install -g json-schema-to-typescript"
    exit 1
fi

# Check if contracts directory exists
if [ ! -d "$CONTRACTS_DIR" ]; then
    echo "❌ Error: $CONTRACTS_DIR does not exist"
    exit 1
fi

# Set up Python virtual environment
echo "📦 Setting up Python virtual environment..."
VENV_DIR="$(pwd)/.venv"
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    source "$VENV_DIR/bin/activate"
    pip install --upgrade pip
    pip install datamodel-code-generator
else
    source "$VENV_DIR/bin/activate"
fi

# Check for json-schema-to-typescript (for TypeScript)
if ! command -v json2ts &> /dev/null; then
    echo "Installing json-schema-to-typescript..."
    npm install -g json-schema-to-typescript
fi

# Generate Python models
echo "🐍 Generating Python Pydantic models..."

# Create a temporary directory for individual model generation
TEMP_DIR=$(mktemp -d)

# Generate models for each schema file individually
for schema_file in "$CONTRACTS_DIR"/*.json; do
    if [ -f "$schema_file" ]; then
        filename=$(basename "$schema_file" .json)
        echo "Processing $filename.json..."
        datamodel-codegen \
            --input-file-type jsonschema \
            --input "$schema_file" \
            --output "$TEMP_DIR/${filename}.py" \
            --output-model-type pydantic_v2.BaseModel \
            --use-schema-description \
            --use-field-description \
            --target-python-version 3.11 \
            --field-constraints \
            --use-annotated
    fi
done

# Combine all generated models using Python for proper deduplication
python3 -c "
import os, re
from collections import OrderedDict

temp_dir = os.environ.get('TEMP_DIR', '$TEMP_DIR')
output_file = os.environ.get('BACKEND_MODELS', '$BACKEND_MODELS')

# Collect all content
all_imports = set()
all_classes = OrderedDict()

for filename in os.listdir(temp_dir):
    if filename.endswith('.py'):
        filepath = os.path.join(temp_dir, filename)
        with open(filepath, 'r') as f:
            content = f.read()
        
        lines = content.split('\n')
        current_class = None
        class_lines = []
        
        for line in lines:
            if line.startswith(('# GENERATED', 'from __future__')):
                continue
            
            if line.startswith(('from ', 'import ')):
                all_imports.add(line)
                continue
            
            if line.startswith('class '):
                if current_class and class_lines:
                    if current_class not in all_classes:
                        all_classes[current_class] = class_lines
                
                match = re.match(r'class (\w+)', line)
                if match:
                    current_class = match.group(1)
                    class_lines = [line]
                else:
                    current_class = None
                    class_lines = []
            elif current_class:
                class_lines.append(line)
        
        if current_class and class_lines:
            if current_class not in all_classes:
                all_classes[current_class] = class_lines

# Write the complete file
with open(output_file, 'w') as f:
    f.write('''# @generated DO NOT EDIT
# GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from JSON schemas in /shared_contracts
# Run \`scripts/generate_contracts.sh\` to regenerate

from __future__ import annotations
from pydantic import BaseModel, Field, Extra, ConfigDict
from typing import List, Optional, Annotated

''')
    for imp in sorted(all_imports):
        f.write(imp + '\n')
    f.write('\n')
    
    for class_name, lines in all_classes.items():
        for line in lines:
            f.write(line + '\n')
        f.write('\n')
" "$TEMP_DIR" "$BACKEND_MODELS"

# Clean up
deactivate
rm -rf "$TEMP_DIR"

# Add additional classes that are not in schemas
cat >> "$BACKEND_MODELS" << EOF

# Additional response models for API endpoints
class QualiaUpdateResponse(BaseModel):
    """Response model for QualiaState update operations."""

    status: str
    message: str
EOF

# Clean up
rm -rf "$TEMP_DIR"

# Generate TypeScript interfaces
echo "📘 Generating TypeScript interfaces..."

# Generate each schema individually as separate files
for schema_file in "$CONTRACTS_DIR"/*.json; do
    if [ -f "$schema_file" ]; then
        filename=$(basename "$schema_file" .json)
        output_file="${FRONTEND_DIR}/src/types/${filename}.d.ts"
        echo "Processing $(basename "$schema_file") -> ${filename}.d.ts..."

        # Create header for individual file
        cat > "$output_file" << EOF
// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schema: ${filename}.json
// Run \`scripts/generate_contracts.sh\` to regenerate
// Last generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

EOF

        # Generate the interface (json2ts adds its own eslint-disable comment and header)
        json2ts "$schema_file" >> "$output_file"
    fi
done

# Also generate combined contracts.ts file
cat > "$FRONTEND_CONTRACTS" << EOF
// @generated DO NOT EDIT
// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from JSON schemas in /shared_contracts
// Run \`scripts/generate_contracts.sh\` to regenerate
// Last generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

EOF

# Import all generated interfaces
for schema_file in "$CONTRACTS_DIR"/*.json; do
    if [ -f "$schema_file" ]; then
        filename=$(basename "$schema_file" .json)
        echo "// Re-export from ${filename}.d.ts" >> "$FRONTEND_CONTRACTS"
        echo "export type { ${filename} } from './${filename}.d.ts';" >> "$FRONTEND_CONTRACTS"
        echo "" >> "$FRONTEND_CONTRACTS"
    fi
done

# Re-export nested types that might be needed
cat >> "$FRONTEND_CONTRACTS" << EOF
// Re-export nested types for convenience
export type { NoteData, LyricData } from './CombatData.d.ts';
EOF

echo "✅ Contracts generated successfully!"
echo "📄 Python models: $BACKEND_MODELS"
echo "📄 TypeScript interfaces: $FRONTEND_CONTRACTS"
echo ""
echo "🚨 IMPORTANT: Do not edit the generated files manually!"
echo "   Modify the JSON schemas in $CONTRACTS_DIR instead."
