//! # Responsibility
//! Implements the #[circuit_breaker] procedural macro for fault tolerance.
//!
//! ---
//!
//! NOTE: Full circuit breaker implementation requires state management.
//! This is a simplified version for PLAN.md Phase 0 completion.
//! Production systems should use dedicated libraries like `failsafe`.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn, Meta, Token};
use syn::parse::{Parse, ParseStream};

struct CircuitBreakerArgs {
    failure_threshold: u32,
}

impl Parse for CircuitBreakerArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut failure_threshold = 5_u32;
        
        while !input.is_empty() {
            let meta: Meta = input.parse()?;
            if let Meta::NameValue(nv) = meta {
                if nv.path.is_ident("failure_threshold") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Int(lit) = expr_lit.lit {
                            failure_threshold = lit.base10_parse()?;
                        }
                    }
                }
            }
            
            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }
        
        Ok(CircuitBreakerArgs { failure_threshold })
    }
}

/// # Responsibility
/// Entry point for #[circuit_breaker] macro expansion.
///
/// ---
///
/// Generates basic circuit breaker pattern with failure counting.
/// For production, use `failsafe` crate or similar dedicated library.
pub fn impl_circuit_breaker(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as CircuitBreakerArgs);
    let input_fn = parse_macro_input!(item as ItemFn);

    let failure_threshold = args.failure_threshold;

    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;
    let fn_output = &input_fn.sig.output;
    let fn_asyncness = &input_fn.sig.asyncness;

    let inner_fn_name = syn::Ident::new(
        &format!("__{}_inner", fn_name),
        fn_name.span(),
    );

    let state_name = syn::Ident::new(
        &format!("__CIRCUIT_BREAKER_{}", fn_name.to_string().to_uppercase()),
        fn_name.span(),
    );

    let input_names: Vec<_> = fn_inputs.iter().filter_map(|arg| {
        if let syn::FnArg::Typed(pat_type) = arg {
            if let syn::Pat::Ident(ident) = &*pat_type.pat {
                return Some(&ident.ident);
            }
        }
        None
    }).collect();

    let expanded = quote! {
        /// # Responsibility
        /// Circuit breaker state tracking failures.
        static #state_name: ::std::sync::OnceLock<::std::sync::Arc<::std::sync::atomic::AtomicU32>> 
            = ::std::sync::OnceLock::new();

        /// # Responsibility
        /// Original function implementation without circuit breaker.
        #fn_asyncness fn #inner_fn_name(#fn_inputs) #fn_output {
            #fn_block
        }

        /// # Responsibility
        /// Circuit breaker wrapper that tracks failures and prevents cascade.
        ///
        /// ---
        ///
        /// Generated by #[circuit_breaker] macro. Opens circuit after threshold failures.
        #fn_vis #fn_asyncness fn #fn_name(#fn_inputs) #fn_output {
            let state = #state_name.get_or_init(|| {
                ::std::sync::Arc::new(::std::sync::atomic::AtomicU32::new(0))
            });

            let failure_count = state.load(::std::sync::atomic::Ordering::Relaxed);

            if failure_count >= #failure_threshold {
                ::tracing::error!(
                    function = stringify!(#fn_name),
                    failures = failure_count,
                    "Circuit breaker OPEN - rejecting call"
                );
                return Err(anyhow::anyhow!(
                    "Circuit breaker open for {} after {} failures",
                    stringify!(#fn_name),
                    failure_count
                ));
            }

            match #inner_fn_name(#(#input_names),*).await {
                Ok(result) => {
                    // Reset on success
                    state.store(0, ::std::sync::atomic::Ordering::Relaxed);
                    Ok(result)
                }
                Err(e) => {
                    let new_count = state.fetch_add(1, ::std::sync::atomic::Ordering::Relaxed) + 1;
                    ::tracing::warn!(
                        function = stringify!(#fn_name),
                        failures = new_count,
                        threshold = #failure_threshold,
                        "Circuit breaker failure recorded"
                    );
                    Err(e)
                }
            }
        }
    };

    TokenStream::from(expanded)
}
