//! # Responsibility
//! Implements the #[handle_event] procedural macro for EventBus subscriptions.
//!
//! ---
//!
//! This module generates the boilerplate code required to:
//! 1. Subscribe to EventBus via `tokio::sync::broadcast::Receiver`
//! 2. Spawn an async task that listens for specific events
//! 3. Handle errors gracefully with tracing
//! 4. Shut down cleanly when EventBus is dropped
//!
//! Replaces `@OnEvent` decorator from TypeScript prototype with compile-time code generation.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn, Path};

/// # Responsibility
/// Entry point for #[handle_event] macro expansion.
///
/// ---
///
/// Parses the attribute arguments (event type) and function definition,
/// then generates the handler registration method.
///
/// # Errors
/// Returns compile error if:
/// - Attribute is not a single path (e.g., `GameEvent::QualiaStateUpdated`)
/// - Function is not async
/// - Function doesn't have `&self` receiver
pub fn impl_handle_event(attr: TokenStream, item: TokenStream) -> TokenStream {
    let event_type = parse_macro_input!(attr as Path);
    let input_fn = parse_macro_input!(item as ItemFn);

    // Validate function signature
    if input_fn.sig.asyncness.is_none() {
        return syn::Error::new_spanned(
            &input_fn.sig.ident,
            "Event handler must be async",
        )
        .to_compile_error()
        .into();
    }

    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;

    // Extract event payload parameter (should be second param after &self)
    let event_param = fn_inputs.iter().nth(1);
    let event_param_ident = match event_param {
        Some(syn::FnArg::Typed(pat_type)) => &pat_type.pat,
        _ => {
            return syn::Error::new_spanned(
                &input_fn.sig.ident,
                "Event handler must have signature: async fn handler(&self, event_data: EventType)",
            )
            .to_compile_error()
            .into();
        }
    };

    // Generate handler registration method name
    let handler_name = syn::Ident::new(
        &format!("{}_handler", fn_name),
        fn_name.span(),
    );

    // Generate expanded code
    let expanded = quote! {
        /// # Responsibility
        /// Original event handler implementation.
        #fn_vis async fn #fn_name(#fn_inputs) {
            #fn_block
        }

        /// # Responsibility
        /// Spawns async task that subscribes to EventBus and routes events to handler.
        ///
        /// ---
        ///
        /// Generated by #[handle_event] macro. Returns `JoinHandle` for lifecycle management.
        #fn_vis fn #handler_name(&self) -> ::tokio::task::JoinHandle<()> {
            let event_bus = self.event_bus.clone();
            let self_clone = self.clone();

            ::tokio::spawn(async move {
                let mut rx = event_bus.subscribe();

                loop {
                    match rx.recv().await {
                        Ok(event) => {
                            // Pattern match on specific event variant
                            if let #event_type(#event_param_ident) = event {
                                self_clone.#fn_name(#event_param_ident).await;
                            }
                        }
                        Err(::tokio::sync::broadcast::error::RecvError::Lagged(skipped)) => {
                            ::tracing::warn!(
                                handler = stringify!(#fn_name),
                                skipped_events = skipped,
                                "Event handler lagging behind EventBus"
                            );
                        }
                        Err(::tokio::sync::broadcast::error::RecvError::Closed) => {
                            ::tracing::info!(
                                handler = stringify!(#fn_name),
                                "EventBus closed, shutting down handler"
                            );
                            break;
                        }
                    }
                }
            })
        }
    };

    TokenStream::from(expanded)
}
