//! # Responsibility
//! Implements the #[instrument] procedural macro for tracing integration.
//!
//! ---
//!
//! Wraps functions with automatic tracing span creation for observability.
//! Integrates with the `tracing` crate to provide structured logging.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn, Meta, Token};
use syn::parse::{Parse, ParseStream};

struct InstrumentArgs {
    level: Option<String>,
    name: Option<String>,
}

impl Parse for InstrumentArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut level = None;
        let mut name = None;
        
        while !input.is_empty() {
            let meta: Meta = input.parse()?;
            if let Meta::NameValue(nv) = meta {
                if nv.path.is_ident("level") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Str(lit) = expr_lit.lit {
                            level = Some(lit.value());
                        }
                    }
                } else if nv.path.is_ident("name") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Str(lit) = expr_lit.lit {
                            name = Some(lit.value());
                        }
                    }
                }
            }
            
            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }
        
        Ok(InstrumentArgs { level, name })
    }
}

/// # Responsibility
/// Entry point for #[instrument] macro expansion.
///
/// ---
///
/// Wraps function with tracing::instrument attribute for automatic span creation.
pub fn impl_instrument(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = if attr.is_empty() {
        InstrumentArgs { level: None, name: None }
    } else {
        parse_macro_input!(attr as InstrumentArgs)
    };
    
    let input_fn = parse_macro_input!(item as ItemFn);

    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;
    let fn_output = &input_fn.sig.output;
    let fn_asyncness = &input_fn.sig.asyncness;
    let fn_generics = &input_fn.sig.generics;

    let span_name = args.name.unwrap_or_else(|| fn_name.to_string());
    let level = args.level.unwrap_or_else(|| "info".to_string());

    let level_ident = syn::Ident::new(&level.to_uppercase(), fn_name.span());

    let expanded = quote! {
        /// # Responsibility
        /// Instrumented function with automatic tracing span.
        ///
        /// ---
        ///
        /// Generated by #[instrument] macro. Creates tracing span on entry/exit.
        #fn_vis #fn_asyncness fn #fn_name #fn_generics (#fn_inputs) #fn_output {
            let span = ::tracing::span!(
                ::tracing::Level::#level_ident,
                #span_name
            );
            let _enter = span.enter();

            #fn_block
        }
    };

    TokenStream::from(expanded)
}
