//! # Responsibility
//! Implements the #[rate_limit] procedural macro for call rate enforcement.
//!
//! ---
//!
//! Wraps functions with rate limiting logic using token bucket algorithm.
//! Prevents excessive function calls that could overload systems.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn, Meta, Token};
use syn::parse::{Parse, ParseStream};

struct RateLimitArgs {
    per_second: u32,
}

impl Parse for RateLimitArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut per_second = 10_u32;
        
        while !input.is_empty() {
            let meta: Meta = input.parse()?;
            if let Meta::NameValue(nv) = meta {
                if nv.path.is_ident("per_second") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Int(lit) = expr_lit.lit {
                            per_second = lit.base10_parse()?;
                        }
                    }
                }
            }
            
            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }
        
        Ok(RateLimitArgs { per_second })
    }
}

/// # Responsibility
/// Entry point for #[rate_limit] macro expansion.
///
/// ---
///
/// Generates rate limiting wrapper using token bucket algorithm with tokio::sync::Semaphore.
pub fn impl_rate_limit(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as RateLimitArgs);
    let input_fn = parse_macro_input!(item as ItemFn);

    let per_second = args.per_second;

    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;
    let fn_output = &input_fn.sig.output;
    let fn_asyncness = &input_fn.sig.asyncness;

    let inner_fn_name = syn::Ident::new(
        &format!("__{}_inner", fn_name),
        fn_name.span(),
    );

    let limiter_name = syn::Ident::new(
        &format!("__RATE_LIMITER_{}", fn_name.to_string().to_uppercase()),
        fn_name.span(),
    );

    let input_names: Vec<_> = fn_inputs.iter().filter_map(|arg| {
        if let syn::FnArg::Typed(pat_type) = arg {
            if let syn::Pat::Ident(ident) = &*pat_type.pat {
                return Some(&ident.ident);
            }
        }
        None
    }).collect();

    let expanded = quote! {
        /// # Responsibility
        /// Rate limiter state for function call throttling.
        static #limiter_name: ::std::sync::OnceLock<::tokio::sync::Semaphore> = ::std::sync::OnceLock::new();

        /// # Responsibility
        /// Original function implementation without rate limiting.
        #fn_asyncness fn #inner_fn_name(#fn_inputs) #fn_output {
            #fn_block
        }

        /// # Responsibility
        /// Rate-limited wrapper that enforces maximum calls per second.
        ///
        /// ---
        ///
        /// Generated by #[rate_limit] macro. Uses semaphore-based token bucket.
        #fn_vis #fn_asyncness fn #fn_name(#fn_inputs) #fn_output {
            let limiter = #limiter_name.get_or_init(|| {
                ::tokio::sync::Semaphore::new(#per_second as usize)
            });

            let _permit = limiter.acquire().await.expect("Semaphore closed");

            // Spawn refill task (simplified - production would use governor crate)
            let result = #inner_fn_name(#(#input_names),*).await;

            // Release permit after minimum interval
            let min_interval_ms = 1000_u64 / #per_second as u64;
            ::tokio::time::sleep(::std::time::Duration::from_millis(min_interval_ms)).await;

            result
        }
    };

    TokenStream::from(expanded)
}
