//! # Responsibility
//! Implements the #[retry] procedural macro for automatic retry logic.
//!
//! ---
//!
//! Wraps async functions with configurable retry attempts and exponential backoff.
//! Logs each retry attempt with tracing for observability.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn, Meta, Token};
use syn::parse::{Parse, ParseStream};

struct RetryArgs {
    max_attempts: u32,
    delay_ms: u64,
    exponential_backoff: bool,
}

impl Parse for RetryArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut max_attempts = 3_u32;
        let mut delay_ms = 100_u64;
        let mut exponential_backoff = false;
        
        while !input.is_empty() {
            let meta: Meta = input.parse()?;
            if let Meta::NameValue(nv) = meta {
                if nv.path.is_ident("max_attempts") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Int(lit) = expr_lit.lit {
                            max_attempts = lit.base10_parse()?;
                        }
                    }
                } else if nv.path.is_ident("delay_ms") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Int(lit) = expr_lit.lit {
                            delay_ms = lit.base10_parse()?;
                        }
                    }
                } else if nv.path.is_ident("exponential_backoff") {
                    if let syn::Expr::Lit(expr_lit) = nv.value {
                        if let syn::Lit::Bool(lit) = expr_lit.lit {
                            exponential_backoff = lit.value;
                        }
                    }
                }
            }
            
            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }
        
        Ok(RetryArgs { max_attempts, delay_ms, exponential_backoff })
    }
}

/// # Responsibility
/// Entry point for #[retry] macro expansion.
///
/// ---
///
/// Parses retry configuration (max_attempts, delay_ms, exponential_backoff)
/// and generates retry loop with error handling.
pub fn impl_retry(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as RetryArgs);
    let input_fn = parse_macro_input!(item as ItemFn);

    let max_attempts = args.max_attempts;
    let delay_ms = args.delay_ms;
    let exponential_backoff = args.exponential_backoff;

    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;
    let fn_output = &input_fn.sig.output;

    // Generate original implementation as separate function
    let inner_fn_name = syn::Ident::new(
        &format!("__{}_inner", fn_name),
        fn_name.span(),
    );

    // Collect input parameter names for passing to inner function
    let input_names: Vec<_> = fn_inputs.iter().filter_map(|arg| {
        if let syn::FnArg::Typed(pat_type) = arg {
            if let syn::Pat::Ident(ident) = &*pat_type.pat {
                return Some(&ident.ident);
            }
        }
        None
    }).collect();

    let backoff_logic = if exponential_backoff {
        quote! {
            let delay = ::std::time::Duration::from_millis(#delay_ms * (2_u64.pow(attempt - 1)));
        }
    } else {
        quote! {
            let delay = ::std::time::Duration::from_millis(#delay_ms);
        }
    };

    let expanded = quote! {
        /// # Responsibility
        /// Original function implementation without retry logic.
        async fn #inner_fn_name(#fn_inputs) #fn_output {
            #fn_block
        }

        /// # Responsibility
        /// Retry wrapper that attempts function up to max_attempts times.
        ///
        /// ---
        ///
        /// Generated by #[retry] macro. Implements exponential backoff if configured.
        #fn_vis async fn #fn_name(#fn_inputs) #fn_output {
            let mut attempt = 1_u32;

            loop {
                match #inner_fn_name(#(#input_names),*).await {
                    Ok(result) => {
                        if attempt > 1 {
                            ::tracing::info!(
                                function = stringify!(#fn_name),
                                attempt = attempt,
                                "Retry succeeded"
                            );
                        }
                        return Ok(result);
                    }
                    Err(e) => {
                        if attempt >= #max_attempts {
                            ::tracing::error!(
                                function = stringify!(#fn_name),
                                attempts = attempt,
                                error = ?e,
                                "All retry attempts exhausted"
                            );
                            return Err(e);
                        }

                        #backoff_logic

                        ::tracing::warn!(
                            function = stringify!(#fn_name),
                            attempt = attempt,
                            max_attempts = #max_attempts,
                            delay_ms = delay.as_millis(),
                            error = ?e,
                            "Retrying after failure"
                        );

                        ::tokio::time::sleep(delay).await;
                        attempt += 1;
                    }
                }
            }
        }
    };

    TokenStream::from(expanded)
}
