//! # Responsibility
//! Implements the #[timeout] procedural macro for automatic timeout enforcement.
//!
//! ---
//!
//! Wraps async functions with tokio::time::timeout to prevent indefinite hangs.
//! Returns TimeoutError if function exceeds specified duration.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn, LitInt};

/// # Responsibility
/// Entry point for #[timeout] macro expansion.
///
/// ---
///
/// Parses timeout duration in milliseconds and wraps function with tokio::time::timeout.
pub fn impl_timeout(attr: TokenStream, item: TokenStream) -> TokenStream {
    let timeout_ms = if attr.is_empty() {
        5000_u64
    } else {
        parse_macro_input!(attr as LitInt).base10_parse().unwrap_or(5000)
    };
    
    let input_fn = parse_macro_input!(item as ItemFn);

    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;
    let fn_output = &input_fn.sig.output;

    let inner_fn_name = syn::Ident::new(
        &format!("__{}_inner", fn_name),
        fn_name.span(),
    );

    // Collect input parameter names for passing to inner function
    let input_names: Vec<_> = fn_inputs.iter().filter_map(|arg| {
        if let syn::FnArg::Typed(pat_type) = arg {
            if let syn::Pat::Ident(ident) = &*pat_type.pat {
                return Some(&ident.ident);
            }
        }
        None
    }).collect();

    let expanded = quote! {
        /// # Responsibility
        /// Original function implementation without timeout.
        async fn #inner_fn_name(#fn_inputs) #fn_output {
            #fn_block
        }

        /// # Responsibility
        /// Timeout wrapper that enforces maximum execution duration.
        ///
        /// ---
        ///
        /// Generated by #[timeout] macro. Returns error if execution exceeds limit.
        #fn_vis async fn #fn_name(#fn_inputs) #fn_output {
            let duration = ::std::time::Duration::from_millis(#timeout_ms);

            match ::tokio::time::timeout(duration, #inner_fn_name(#(#input_names),*)).await {
                Ok(result) => result,
                Err(_elapsed) => {
                    ::tracing::error!(
                        function = stringify!(#fn_name),
                        timeout_ms = #timeout_ms,
                        "Function execution timed out"
                    );
                    Err(anyhow::anyhow!(
                        "Function {} timed out after {}ms",
                        stringify!(#fn_name),
                        #timeout_ms
                    ))
                }
            }
        }
    };

    TokenStream::from(expanded)
}
