[package]
name = "shared_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
shaku.workspace = true
async-trait.workspace = true
anyhow.workspace = true
tokio.workspace = true

[features]
default = []
wasm = ["uuid/js", "chrono/wasmbind"]
