//! # Responsibility
//! Defines all audio-related data structures for musical analysis and synthesis.
//!
//! ---
//!
//! This module contains contracts for the Harmony Engine (backend) and
//! Performance Engine (frontend) as defined in MUSIC.RUST.md. These structures
//! enable generative music that respects musical theory while being procedural.

use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
use super::game_state::Vec2;
use super::combat_data::TimeSignature;

/// # Responsibility
/// Defines a single harmonic region within a song's timeline.
///
/// ---
///
/// Each context represents a chord or harmonic area in the song. The backend
/// uses these to validate player actions against musical theory, ensuring
/// all generative music is harmonically coherent.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HarmonicContext {
    pub start_time_sec: f64,
    pub end_time_sec: f64,
    pub chord: String,
    pub scale: Vec<String>,
}

/// # Responsibility
/// Contains the complete musical theory analysis of a song.
///
/// ---
///
/// This is the "ruleset" for all generative music. Generated by the
/// HarmonyAnalysisService (backend) during pre-processing and consulted
/// in real-time during gameplay to adjudicate musical actions.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HarmonyMap {
    pub song_id: String,
    pub key_signature: String,
    pub time_signature: TimeSignature,
    pub progression: Vec<HarmonicContext>,
}

/// # Responsibility
/// Defines synthesis parameters for procedural audio generation.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SynthParameters {
    pub oscillator1_type: String,
    pub oscillator2_type: Option<String>,
    pub filter_cutoff: f32,
    pub filter_resonance: f32,
    pub adsr_attack: f32,
    pub adsr_decay: f32,
    pub adsr_sustain: f32,
    pub adsr_release: f32,
}

impl Default for SynthParameters {
    fn default() -> Self {
        Self {
            oscillator1_type: "sine".to_string(),
            oscillator2_type: None,
            filter_cutoff: 1000.0,
            filter_resonance: 1.0,
            adsr_attack: 0.01,
            adsr_decay: 0.1,
            adsr_sustain: 0.7,
            adsr_release: 0.3,
        }
    }
}

/// # Responsibility
/// Defines the type of instrument patch (sampler or synthesizer).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum PatchType {
    Sampler {
        sample_map_url: String,
    },
    Synth {
        parameters: SynthParameters,
    },
}

/// # Responsibility
/// Defines a playable instrument, either sample-based or synthesized.
///
/// ---
///
/// Player and Boss are assigned collections of these per level. When a
/// musical action occurs, the GameLogicService specifies which patch to use,
/// and the AudioService renders it accordingly.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstrumentPatch {
    pub id: String,
    pub name: String,
    pub patch_type: PatchType,
}

/// # Responsibility
/// Defines an audio layer for spatial audio mixing.
///
/// ---
///
/// Used for 8D audio positioning and mixing multiple audio sources
/// (background track, player notes, boss notes, ambient effects).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioLayer {
    pub id: String,
    pub volume: f32,
    pub pan: f32,
    pub spatial_position: Option<Vec2>,
    pub reverb: f32,
    pub delay: f32,
}

impl Default for AudioLayer {
    fn default() -> Self {
        Self {
            id: "default".to_string(),
            volume: 1.0,
            pan: 0.0,
            spatial_position: None,
            reverb: 0.0,
            delay: 0.0,
        }
    }
}

/// # Responsibility
/// Represents a note to be played by the generative music system.
///
/// ---
///
/// This is the core event for all musical generation. Emitted by the backend
/// (GameLogicService) when player/boss actions are adjudicated. Consumed by
/// the frontend (AudioService) to generate sound and visual effects.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PlayGenerativeNote {
    pub note_pitch: u8,
    pub velocity: u8,
    pub instrument_patch_id: String,
    pub position: Vec2,
    pub duration_ms: Option<u32>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_harmony_map_serialization() {
        let map = HarmonyMap {
            song_id: "test_song".to_string(),
            key_signature: "C Major".to_string(),
            time_signature: TimeSignature {
                numerator: 4,
                denominator: 4,
            },
            progression: vec![
                HarmonicContext {
                    start_time_sec: 0.0,
                    end_time_sec: 4.0,
                    chord: "C".to_string(),
                    scale: vec!["C".to_string(), "D".to_string(), "E".to_string()],
                },
            ],
        };

        let json = serde_json::to_string(&map).unwrap();
        assert!(json.contains("test_song"));
        assert!(json.contains("C Major"));

        let deserialized: HarmonyMap = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, map);
    }

    #[test]
    fn test_instrument_patch_serialization() {
        let patch = InstrumentPatch {
            id: "crystal_bell".to_string(),
            name: "Crystal Bell".to_string(),
            patch_type: PatchType::Sampler {
                sample_map_url: "samples/bell.json".to_string(),
            },
        };

        let json = serde_json::to_string(&patch).unwrap();
        assert!(json.contains("crystal_bell"));
        assert!(json.contains("sampler"));

        let deserialized: InstrumentPatch = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, patch);
    }

    #[test]
    fn test_play_generative_note_serialization() {
        let note = PlayGenerativeNote {
            note_pitch: 60,
            velocity: 110,
            instrument_patch_id: "crystal_bell".to_string(),
            position: Vec2::new(0.0, 0.0),
            duration_ms: Some(500),
        };

        let json = serde_json::to_string(&note).unwrap();
        assert!(json.contains("60"));
        assert!(json.contains("110"));
        assert!(json.contains("crystal_bell"));

        let deserialized: PlayGenerativeNote = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, note);
    }

    #[test]
    fn test_synth_parameters_default() {
        let params = SynthParameters::default();
        assert_eq!(params.oscillator1_type, "sine");
        assert_eq!(params.filter_cutoff, 1000.0);
        assert_eq!(params.adsr_attack, 0.01);
    }
}
