//! # Responsibility
//! Defines all audio-related data structures for musical gameplay.
//!
//! ---
//!
//! This module implements the contracts specified in MUSIC.RUST.md for the
//! Harmony Engine and Performance Engine. All structures support serialization
//! for transmission between backend (analysis) and frontend (synthesis).

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// # Responsibility
/// Represents a musical chord with root note and quality.
///
/// ---
///
/// Derived from the Harmony Engine's analysis of the song's musical theory.
/// Used to determine harmonic consonance/dissonance of player actions.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Chord {
    /// Root note in MIDI format (60 = Middle C)
    pub root_note: u8,
    /// Chord quality (e.g., "major", "minor", "diminished", "augmented")
    pub quality: String,
    /// Optional 7th, 9th extensions
    pub extensions: Vec<String>,
}

/// # Responsibility
/// Maps time positions to musical information for a song.
///
/// ---
///
/// Generated by the backend's `HarmonyAnalysisService` during pre-processing.
/// Contains the "musical theory" of the song that drives gameplay mechanics.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HarmonyMap {
    /// Song identifier
    pub song_id: String,
    /// Detected key signature (e.g., "C", "Am")
    pub key_signature: String,
    /// Tempo in BPM
    pub bpm: f32,
    /// Time signature (e.g., "4/4", "3/4")
    pub time_signature: String,
    /// Map of timestamp (ms) to active chord
    pub chord_progression: Vec<(f64, Chord)>,
    /// Map of timestamp (ms) to beat strength (0.0 to 1.0)
    pub beat_map: Vec<(f64, f32)>,
}

/// # Responsibility
/// Defines the audio characteristics of an instrument patch.
///
/// ---
///
/// Used by the frontend's Performance Engine to generate/play sounds.
/// Different patches are assigned to player, boss, and environment.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstrumentPatch {
    /// Patch identifier
    pub id: String,
    /// Human-readable name
    pub name: String,
    /// Synthesis type ("sampler" or "synth")
    pub synthesis_type: SynthesisType,
    /// For sampler: path to sample bank
    pub sample_bank_path: Option<String>,
    /// For synth: waveform type
    pub waveform: Option<Waveform>,
    /// ADSR envelope settings
    pub envelope: EnvelopeSettings,
    /// Audio effects chain
    pub effects: Vec<AudioEffect>,
}

/// # Responsibility
/// Enumerates synthesis methods for audio generation.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SynthesisType {
    Sampler,
    Synth,
}

/// # Responsibility
/// Enumerates waveform types for synthesis.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Waveform {
    Sine,
    Square,
    Sawtooth,
    Triangle,
}

/// # Responsibility
/// Defines ADSR envelope for sound shaping.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct EnvelopeSettings {
    /// Attack time in seconds
    pub attack: f32,
    /// Decay time in seconds
    pub decay: f32,
    /// Sustain level (0.0 to 1.0)
    pub sustain: f32,
    /// Release time in seconds
    pub release: f32,
}

/// # Responsibility
/// Enumerates audio effect types.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum AudioEffect {
    Reverb { room_size: f32, damping: f32 },
    Delay { time_ms: f32, feedback: f32 },
    Distortion { drive: f32 },
    Filter { cutoff_hz: f32, resonance: f32 },
}

/// # Responsibility
/// Represents a layer in the adaptive music system.
///
/// ---
///
/// Multiple layers can be mixed based on game state (e.g., combat intensity).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioLayer {
    /// Layer identifier
    pub id: String,
    /// Audio file path
    pub file_path: String,
    /// Current volume (0.0 to 1.0)
    pub volume: f32,
    /// Target volume for smooth transitions
    pub target_volume: f32,
    /// Is this layer currently active?
    pub is_active: bool,
}

/// # Responsibility
/// Command to play a generative note in the Performance Engine.
///
/// ---
///
/// Sent from backend to frontend when player/boss actions trigger sounds.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PlayGenerativeNote {
    /// MIDI note number (60 = Middle C)
    pub note: u8,
    /// Velocity (0.0 to 1.0)
    pub velocity: f32,
    /// Duration in seconds
    pub duration: f32,
    /// Instrument patch to use
    pub patch_id: String,
    /// Optional spatial position for 8D audio
    pub spatial_position: Option<(f32, f32, f32)>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_harmony_map_serialization() {
        let harmony_map = HarmonyMap {
            song_id: "test_song".to_string(),
            key_signature: "C".to_string(),
            bpm: 120.0,
            time_signature: "4/4".to_string(),
            chord_progression: vec![
                (0.0, Chord {
                    root_note: 60,
                    quality: "major".to_string(),
                    extensions: vec![],
                }),
            ],
            beat_map: vec![(0.0, 1.0), (500.0, 0.5)],
        };

        let json = serde_json::to_string(&harmony_map).expect("Failed to serialize");
        let deserialized: HarmonyMap =
            serde_json::from_str(&json).expect("Failed to deserialize");

        assert_eq!(harmony_map, deserialized);
    }

    #[test]
    fn test_instrument_patch_synth() {
        let patch = InstrumentPatch {
            id: "synth_lead".to_string(),
            name: "Lead Synth".to_string(),
            synthesis_type: SynthesisType::Synth,
            sample_bank_path: None,
            waveform: Some(Waveform::Sawtooth),
            envelope: EnvelopeSettings {
                attack: 0.01,
                decay: 0.1,
                sustain: 0.7,
                release: 0.3,
            },
            effects: vec![AudioEffect::Reverb {
                room_size: 0.5,
                damping: 0.3,
            }],
        };

        let json = serde_json::to_string(&patch).expect("Failed to serialize");
        let deserialized: InstrumentPatch =
            serde_json::from_str(&json).expect("Failed to deserialize");

        assert_eq!(patch, deserialized);
    }

    #[test]
    fn test_play_generative_note() {
        let note = PlayGenerativeNote {
            note: 60,
            velocity: 0.8,
            duration: 0.5,
            patch_id: "piano".to_string(),
            spatial_position: Some((0.0, 0.0, 1.0)),
        };

        let json = serde_json::to_string(&note).expect("Failed to serialize");
        assert!(json.contains(r#""note":60"#));
    }

    #[test]
    fn test_audio_effect_variants() {
        let effects = vec![
            AudioEffect::Reverb {
                room_size: 0.8,
                damping: 0.5,
            },
            AudioEffect::Delay {
                time_ms: 250.0,
                feedback: 0.4,
            },
            AudioEffect::Distortion { drive: 0.6 },
            AudioEffect::Filter {
                cutoff_hz: 1000.0,
                resonance: 0.3,
            },
        ];

        for effect in effects {
            let json = serde_json::to_string(&effect).expect("Failed to serialize");
            let _deserialized: AudioEffect =
                serde_json::from_str(&json).expect("Failed to deserialize");
        }
    }
}
