//! # Responsibility
//! Defines audio system contracts per MUSIC.RUST.md specifications.
//!
//! ---
//!
//! Contains HarmonyMap, InstrumentPatch, and audio event structures
//! that bridge the Harmony Engine (backend) and Performance Engine (frontend).

use crate::utils::Vec2;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// # Responsibility
/// Defines a single harmonic region within a song's timeline.
///
/// ---
///
/// Used by HarmonyAnalysisService to map song timeline to musical theory.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HarmonicContext {
    pub start_time_sec: f64,
    pub end_time_sec: f64,
    pub chord: String, // e.g., "Am7", "G", "Cmaj7"
    pub scale: Vec<String>, // e.g., ["A", "B", "C", "D", "E", "F", "G"]
}

/// # Responsibility
/// Contains the complete musical theory analysis of a song.
///
/// ---
///
/// This map is the "ruleset" for all generative music.
/// Generated by HarmonyAnalysisService, consumed by GameLogicService.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HarmonyMap {
    pub song_id: String,
    pub key_signature: String, // e.g., "C Major"
    pub time_signature: (u8, u8), // e.g., (4, 4)
    pub bpm: f32,
    pub progression: Vec<HarmonicContext>,
}

/// # Responsibility
/// Defines synthesizer parameters for procedural sound generation.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SynthParameters {
    pub oscillator1_type: String, // "sine", "square", "sawtooth"
    pub oscillator2_type: Option<String>,
    pub filter_cutoff: f32,
    pub adsr_attack: f32,
    pub adsr_decay: f32,
    pub adsr_sustain: f32,
    pub adsr_release: f32,
}

impl Default for SynthParameters {
    fn default() -> Self {
        Self {
            oscillator1_type: "sine".to_string(),
            oscillator2_type: None,
            filter_cutoff: 1000.0,
            adsr_attack: 0.01,
            adsr_decay: 0.1,
            adsr_sustain: 0.5,
            adsr_release: 0.3,
        }
    }
}

/// # Responsibility
/// Enumerates the type of instrument patch (sampler or synthesizer).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum PatchType {
    /// Sample-based instrument (loads .wav files)
    Sampler {
        sample_map_url: String, // URL to JSON mapping MIDI notes to .wav files
    },
    /// Synthesized instrument (procedural generation)
    Synth { parameters: SynthParameters },
}

/// # Responsibility
/// Defines a playable instrument, either sample-based or synthesized.
///
/// ---
///
/// Player and Boss will have a collection of these assigned per level.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstrumentPatch {
    pub id: String,
    pub name: String,
    pub patch_type: PatchType,
}

/// # Responsibility
/// Represents an audio layer in the 8D audio mix.
///
/// ---
///
/// Each layer can be individually controlled (volume, pan, effects).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioLayer {
    pub id: String,
    pub name: String,
    pub volume: f32, // 0.0 to 1.0
    pub is_muted: bool,
    pub spatial_position: Option<Vec2>, // For 8D audio
}

/// # Responsibility
/// Represents complete song data loaded from configuration.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SongData {
    pub id: String,
    pub title: String,
    pub artist: String,
    pub duration_sec: f64,
    pub audio_url: String,
    pub harmony_map: HarmonyMap,
    pub layers: Vec<AudioLayer>,
}

// ============================================================================
// Frontend Audio Engine Structures (DATA.RUST.md Section 5)
// ============================================================================

/// # Responsibility
/// Enumerates the types of audio events for the frontend AudioEngineService.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AudioEventType {
    PlaySfx,
    StopSfx,
    PlayMusic,
    StopMusic,
    Crossfade,
    VolumeChange,
    PitchShift,
    ApplyFilter,
    TriggerStinger,
    SyncBeat,
}

/// # Responsibility
/// Enumerates audio filter types.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FilterType {
    Lowpass,
    Highpass,
    Bandpass,
    Reverb,
    Delay,
    Distortion,
}

/// # Responsibility
/// Defines playback parameters for an audio event.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioEventParameters {
    pub volume: Option<f32>,
    pub pitch: Option<f32>,
    pub pan: Option<f32>,
    pub fade_in_sec: Option<f64>,
    pub fade_out_sec: Option<f64>,
    pub loop_playback: Option<bool>,
    pub priority: Option<f32>,
}

/// # Responsibility
/// Defines audio filter settings for an audio event.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioFilterSettings {
    #[serde(rename = "type")]
    pub filter_type: Option<FilterType>,
    pub frequency: Option<f32>,
    pub resonance: Option<f32>,
    pub wet_dry_mix: Option<f32>,
}

/// # Responsibility
/// Defines spatial audio positioning data.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SpatialData {
    pub position: Option<crate::utils::Vec3>,
    pub max_distance: Option<f32>,
    pub rolloff_factor: Option<f32>,
}

/// # Responsibility
/// Defines a command for the frontend audio engine to execute.
///
/// ---
///
/// These events are generated by frontend services and processed by
/// AudioEngineService to control playback, mixing, and effects.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioEvent {
    pub id: String,
    #[serde(rename = "type")]
    pub event_type: AudioEventType,
    pub timestamp: f64,
    pub audio_clip_id: Option<String>,
    pub layer_id: Option<String>,
    pub parameters: Option<AudioEventParameters>,
    pub filter_settings: Option<AudioFilterSettings>,
    pub spatial_data: Option<SpatialData>,
    pub trigger_condition: Option<crate::contracts::combat_data::QualiaThreshold>,
}

/// # Responsibility
/// Enumerates audio layer types for mixing organization.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AudioLayerType {
    Music,
    Sfx,
    Ambient,
    Voice,
    Ui,
}

/// # Responsibility
/// Represents an active audio source within a mixing layer.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ActiveAudioSource {
    pub source_id: String,
    pub audio_clip_id: String,
    pub start_time: f64,
    pub volume: f32,
    pub is_looping: bool,
}

/// # Responsibility
/// Represents an effect applied to an audio layer.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LayerEffect {
    pub effect_id: String,
    #[serde(rename = "type")]
    pub effect_type: String, // e.g., "compressor", "eq"
    pub enabled: bool,
    pub parameters: Option<std::collections::HashMap<String, f32>>,
}

/// # Responsibility
/// Defines a complete mixing layer with sources and effects.
///
/// ---
///
/// Used by frontend AudioEngineService to organize and process audio.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioLayerFull {
    pub id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub layer_type: AudioLayerType,
    pub volume: f32,
    pub muted: bool,
    pub solo: bool,
    pub active_sources: Vec<ActiveAudioSource>,
    pub effects: Vec<LayerEffect>,
    pub qualia_modulation: Option<std::collections::HashMap<String, bool>>,
}

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // Core Audio Tests
    // ========================================================================

    #[test]
    fn test_harmonic_context_serialization() {
        let context = HarmonicContext {
            start_time_sec: 0.0,
            end_time_sec: 4.0,
            chord: "Cmaj7".to_string(),
            scale: vec!["C".to_string(), "D".to_string(), "E".to_string()],
        };

        let json = serde_json::to_string(&context).unwrap();
        let deserialized: HarmonicContext = serde_json::from_str(&json).unwrap();

        assert_eq!(context, deserialized);
    }

    #[test]
    fn test_harmony_map_serialization() {
        let map = HarmonyMap {
            song_id: "test_song".to_string(),
            key_signature: "C Major".to_string(),
            time_signature: (4, 4),
            bpm: 120.0,
            progression: vec![],
        };

        let json = serde_json::to_string(&map).unwrap();
        let deserialized: HarmonyMap = serde_json::from_str(&json).unwrap();

        assert_eq!(map, deserialized);
    }

    #[test]
    fn test_instrument_patch_sampler() {
        let patch = InstrumentPatch {
            id: "piano_patch".to_string(),
            name: "Grand Piano".to_string(),
            patch_type: PatchType::Sampler {
                sample_map_url: "/assets/piano_samples.json".to_string(),
            },
        };

        let json = serde_json::to_string(&patch).unwrap();
        assert!(json.contains(r#""type":"sampler""#));
    }

    #[test]
    fn test_instrument_patch_synth() {
        let patch = InstrumentPatch {
            id: "synth_patch".to_string(),
            name: "Ethereal Synth".to_string(),
            patch_type: PatchType::Synth {
                parameters: SynthParameters::default(),
            },
        };

        let json = serde_json::to_string(&patch).unwrap();
        assert!(json.contains(r#""type":"synth""#));
    }

    #[test]
    fn test_synth_parameters_default() {
        let params = SynthParameters::default();
        assert_eq!(params.oscillator1_type, "sine");
        assert_eq!(params.adsr_attack, 0.01);
    }

    // ========================================================================
    // Frontend Audio Events Tests
    // ========================================================================

    #[test]
    fn test_audio_event_type_enum() {
        let types = vec![
            AudioEventType::PlaySfx,
            AudioEventType::StopSfx,
            AudioEventType::PlayMusic,
            AudioEventType::SyncBeat,
        ];

        for event_type in types {
            let json = serde_json::to_string(&event_type).unwrap();
            let deserialized: AudioEventType = serde_json::from_str(&json).unwrap();
            assert_eq!(event_type, deserialized);
        }
    }

    #[test]
    fn test_filter_type_enum() {
        let filters = vec![
            FilterType::Lowpass,
            FilterType::Highpass,
            FilterType::Reverb,
        ];

        for filter in filters {
            let json = serde_json::to_string(&filter).unwrap();
            let deserialized: FilterType = serde_json::from_str(&json).unwrap();
            assert_eq!(filter, deserialized);
        }
    }

    #[test]
    fn test_audio_event_parameters_serialization() {
        let params = AudioEventParameters {
            volume: Some(0.8),
            pitch: Some(1.2),
            pan: Some(0.5),
            fade_in_sec: Some(0.5),
            fade_out_sec: Some(1.0),
            loop_playback: Some(true),
            priority: Some(1.0),
        };

        let json = serde_json::to_string(&params).unwrap();
        let deserialized: AudioEventParameters = serde_json::from_str(&json).unwrap();

        assert_eq!(params, deserialized);
    }

    #[test]
    fn test_audio_filter_settings_serialization() {
        let settings = AudioFilterSettings {
            filter_type: Some(FilterType::Lowpass),
            frequency: Some(1000.0),
            resonance: Some(0.7),
            wet_dry_mix: Some(0.5),
        };

        let json = serde_json::to_string(&settings).unwrap();
        let deserialized: AudioFilterSettings = serde_json::from_str(&json).unwrap();

        assert_eq!(settings, deserialized);
    }

    #[test]
    fn test_audio_layer_type_enum() {
        let types = vec![
            AudioLayerType::Music,
            AudioLayerType::Sfx,
            AudioLayerType::Ambient,
            AudioLayerType::Voice,
            AudioLayerType::Ui,
        ];

        for layer_type in types {
            let json = serde_json::to_string(&layer_type).unwrap();
            let deserialized: AudioLayerType = serde_json::from_str(&json).unwrap();
            assert_eq!(layer_type, deserialized);
        }
    }

    #[test]
    fn test_active_audio_source_serialization() {
        let source = ActiveAudioSource {
            source_id: "src_001".to_string(),
            audio_clip_id: "clip_001".to_string(),
            start_time: 1500.0,
            volume: 0.9,
            is_looping: false,
        };

        let json = serde_json::to_string(&source).unwrap();
        let deserialized: ActiveAudioSource = serde_json::from_str(&json).unwrap();

        assert_eq!(source, deserialized);
    }

    #[test]
    fn test_layer_effect_serialization() {
        let mut params = std::collections::HashMap::new();
        params.insert("gain".to_string(), 1.5);

        let effect = LayerEffect {
            effect_id: "effect_001".to_string(),
            effect_type: "compressor".to_string(),
            enabled: true,
            parameters: Some(params),
        };

        let json = serde_json::to_string(&effect).unwrap();
        let deserialized: LayerEffect = serde_json::from_str(&json).unwrap();

        assert_eq!(effect, deserialized);
    }

    #[test]
    fn test_audio_layer_full_serialization() {
        let layer = AudioLayerFull {
            id: "layer_music".to_string(),
            name: "Music".to_string(),
            layer_type: AudioLayerType::Music,
            volume: 0.8,
            muted: false,
            solo: false,
            active_sources: vec![],
            effects: vec![],
            qualia_modulation: None,
        };

        let json = serde_json::to_string(&layer).unwrap();
        let deserialized: AudioLayerFull = serde_json::from_str(&json).unwrap();

        assert_eq!(layer, deserialized);
    }
}

// NOTE: PlayGenerativeNote is defined in shared_core::events::audio_events
// Re-export here for convenience
pub use crate::events::audio_events::PlayGenerativeNote;
