//! # Responsibility
//! Defines player input action contracts per DATA.RUST.md Section 3.4.
//!
//! ---
//!
//! Contains all player input actions, musical analysis structures,
//! and rhythm/harmonic detection types.

use crate::contracts::combat_data::ComboActionType;
use crate::contracts::game_state::QualiaState;
use crate::utils::Vec2;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// # Responsibility
/// Enumerates all possible player input actions in the game.
///
/// ---
///
/// This tagged enum uses Serde's `tag = "type"` for clean JSON serialization.
/// Each variant contains the relevant data for that action type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum PlayerAction {
    /// Player pressed a musical key (Q, E, R, T, F, G, C)
    KeyPressed {
        key: char,
        timestamp: f64,
        accuracy: f32, // 0.0 to 1.0
    },
    /// Player initiated a dash
    DashInitiated {
        direction: Vec2,
        timestamp: f64,
        on_beat: bool,
    },
    /// Player attempted a parry
    ParryAttempted { timestamp: f64 },
    /// Player activated ultimate ability
    UltimateActivated { timestamp: f64 },
    /// Player moved (mouse position update)
    MouseMoved { position: Vec2, timestamp: f64 },
}

// ============================================================================
// Musical Input Analysis (DATA.RUST.md Section 3.4)
// ============================================================================

/// # Responsibility
/// Enumerates detected rhythmic patterns in player input.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RhythmicPattern {
    None,
    Steady,
    Syncopated,
    Polyrhythmic,
    Chaotic,
}

/// # Responsibility
/// Enumerates accuracy levels for individual input actions.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InputAccuracy {
    Perfect,
    Good,
    Ok,
    Miss,
}

/// # Responsibility
/// Represents a single recent input action with timing analysis.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RecentInput {
    pub action: ComboActionType,
    pub timestamp: f64,
    /// Timing offset from ideal beat in milliseconds
    pub timing_offset: f64,
    pub accuracy: InputAccuracy,
}

/// # Responsibility
/// Contains complete musical analysis of recent player input.
///
/// ---
///
/// Generated by backend GameLogicService, used to calculate QualiaState
/// and determine emergent combo patterns. This is the bridge between
/// raw player input and musical interpretation.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MusicalInputAnalysis {
    pub timestamp: f64,
    pub recent_inputs: Vec<RecentInput>,
    /// Consistency of rhythm (0.0 = chaotic, 1.0 = perfect sync)
    pub rhythmic_consistency: f32,
    pub detected_pattern: RhythmicPattern,
    /// Alignment with current harmonic context (0.0 = dissonant, 1.0 = harmonic)
    pub harmonic_alignment: f32,
    /// Progress in completing a musical phrase (0.0 = start, 1.0 = complete)
    pub phrase_completion: f32,
    /// Dynamic range of input intensity (0.0 = monotone, 1.0 = varied)
    pub dynamic_range: f32,
    /// Suggested QualiaState modifiers based on input analysis
    pub suggested_qualia_shift: QualiaState,
}

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // Player Action Tests
    // ========================================================================

    #[test]
    fn test_player_action_key_pressed_serialization() {
        let action = PlayerAction::KeyPressed {
            key: 'Q',
            timestamp: 1000.0,
            accuracy: 0.95,
        };

        let json = serde_json::to_string(&action).unwrap();
        let deserialized: PlayerAction = serde_json::from_str(&json).unwrap();

        assert_eq!(action, deserialized);
    }

    #[test]
    fn test_player_action_dash_serialization() {
        let action = PlayerAction::DashInitiated {
            direction: Vec2::new(1.0, 0.0),
            timestamp: 2000.0,
            on_beat: true,
        };

        let json = serde_json::to_string(&action).unwrap();
        assert!(json.contains(r#""type":"dashInitiated""#));
    }

    // ========================================================================
    // Musical Analysis Tests
    // ========================================================================

    #[test]
    fn test_rhythmic_pattern_enum() {
        let patterns = vec![
            RhythmicPattern::None,
            RhythmicPattern::Steady,
            RhythmicPattern::Syncopated,
            RhythmicPattern::Polyrhythmic,
            RhythmicPattern::Chaotic,
        ];

        for pattern in patterns {
            let json = serde_json::to_string(&pattern).unwrap();
            let deserialized: RhythmicPattern = serde_json::from_str(&json).unwrap();
            assert_eq!(pattern, deserialized);
        }
    }

    #[test]
    fn test_input_accuracy_enum() {
        let accuracies = vec![
            InputAccuracy::Perfect,
            InputAccuracy::Good,
            InputAccuracy::Ok,
            InputAccuracy::Miss,
        ];

        for accuracy in accuracies {
            let json = serde_json::to_string(&accuracy).unwrap();
            let deserialized: InputAccuracy = serde_json::from_str(&json).unwrap();
            assert_eq!(accuracy, deserialized);
        }
    }

    #[test]
    fn test_recent_input_serialization() {
        let input = RecentInput {
            action: ComboActionType::Hit,
            timestamp: 1500.0,
            timing_offset: -5.0,
            accuracy: InputAccuracy::Perfect,
        };

        let json = serde_json::to_string(&input).unwrap();
        let deserialized: RecentInput = serde_json::from_str(&json).unwrap();

        assert_eq!(input, deserialized);
    }

    #[test]
    fn test_musical_input_analysis_serialization() {
        let analysis = MusicalInputAnalysis {
            timestamp: 1500.0,
            recent_inputs: vec![],
            rhythmic_consistency: 0.9,
            detected_pattern: RhythmicPattern::Steady,
            harmonic_alignment: 0.85,
            phrase_completion: 0.5,
            dynamic_range: 0.7,
            suggested_qualia_shift: QualiaState::default(),
        };

        let json = serde_json::to_string(&analysis).unwrap();
        let deserialized: MusicalInputAnalysis = serde_json::from_str(&json).unwrap();

        assert_eq!(analysis, deserialized);
    }

    #[test]
    fn test_musical_input_analysis_with_recent_inputs() {
        let analysis = MusicalInputAnalysis {
            timestamp: 2000.0,
            recent_inputs: vec![
                RecentInput {
                    action: ComboActionType::Hit,
                    timestamp: 1900.0,
                    timing_offset: 2.0,
                    accuracy: InputAccuracy::Good,
                },
                RecentInput {
                    action: ComboActionType::Dash,
                    timestamp: 1950.0,
                    timing_offset: -1.0,
                    accuracy: InputAccuracy::Perfect,
                },
            ],
            rhythmic_consistency: 0.95,
            detected_pattern: RhythmicPattern::Syncopated,
            harmonic_alignment: 0.9,
            phrase_completion: 0.75,
            dynamic_range: 0.8,
            suggested_qualia_shift: QualiaState::default(),
        };

        let json = serde_json::to_string(&analysis).unwrap();
        let deserialized: MusicalInputAnalysis = serde_json::from_str(&json).unwrap();

        assert_eq!(analysis, deserialized);
        assert_eq!(analysis.recent_inputs.len(), 2);
    }
}
